DROP TABLE `academy_courses`;--> statement-breakpoint
DROP TABLE `academy_houses`;--> statement-breakpoint
DROP TABLE `academy_languages`;--> statement-breakpoint
DROP TABLE `academy_lessons`;--> statement-breakpoint
DROP TABLE `allocation_pots`;--> statement-breakpoint
DROP TABLE `allocation_transactions`;--> statement-breakpoint
DROP TABLE `approvals`;--> statement-breakpoint
DROP TABLE `assets`;--> statement-breakpoint
DROP TABLE `audit_events`;--> statement-breakpoint
DROP TABLE `audit_requests`;--> statement-breakpoint
DROP TABLE `bot_actions`;--> statement-breakpoint
DROP TABLE `bot_conversations`;--> statement-breakpoint
DROP TABLE `bot_messages`;--> statement-breakpoint
DROP TABLE `bots`;--> statement-breakpoint
DROP TABLE `contact_submissions`;--> statement-breakpoint
DROP TABLE `course_completion_certificates`;--> statement-breakpoint
DROP TABLE `course_progress`;--> statement-breakpoint
DROP TABLE `distribution_events`;--> statement-breakpoint
DROP TABLE `distribution_rules`;--> statement-breakpoint
DROP TABLE `divine_stem_modules`;--> statement-breakpoint
DROP TABLE `document_access`;--> statement-breakpoint
DROP TABLE `document_access_log`;--> statement-breakpoint
DROP TABLE `document_folders`;--> statement-breakpoint
DROP TABLE `document_versions`;--> statement-breakpoint
DROP TABLE `economic_health_indicators`;--> statement-breakpoint
DROP TABLE `email_sends`;--> statement-breakpoint
DROP TABLE `email_templates`;--> statement-breakpoint
DROP TABLE `financial_errors`;--> statement-breakpoint
DROP TABLE `flame_lock_codes`;--> statement-breakpoint
DROP TABLE `fraud_flags`;--> statement-breakpoint
DROP TABLE `gift_activation_attempts`;--> statement-breakpoint
DROP TABLE `gift_sale_ratios`;--> statement-breakpoint
DROP TABLE `gift_tokens`;--> statement-breakpoint
DROP TABLE `guardian_access`;--> statement-breakpoint
DROP TABLE `house_businesses`;--> statement-breakpoint
DROP TABLE `house_ledger_transactions`;--> statement-breakpoint
DROP TABLE `house_ledgers`;--> statement-breakpoint
DROP TABLE `house_members`;--> statement-breakpoint
DROP TABLE `houses`;--> statement-breakpoint
DROP TABLE `incidents`;--> statement-breakpoint
DROP TABLE `income_events`;--> statement-breakpoint
DROP TABLE `inflow_capture`;--> statement-breakpoint
DROP TABLE `inheritance_queue`;--> statement-breakpoint
DROP TABLE `integrity_triggers`;--> statement-breakpoint
DROP TABLE `language_lessons`;--> statement-breakpoint
DROP TABLE `ledger_access_logs`;--> statement-breakpoint
DROP TABLE `living_scrolls`;--> statement-breakpoint
DROP TABLE `luvchain_blocks`;--> statement-breakpoint
DROP TABLE `luvchain_smart_contracts`;--> statement-breakpoint
DROP TABLE `luvchain_transactions`;--> statement-breakpoint
DROP TABLE `main_house_ledger`;--> statement-breakpoint
DROP TABLE `mastery_certificates`;--> statement-breakpoint
DROP TABLE `metrics`;--> statement-breakpoint
DROP TABLE `mirror_tokens`;--> statement-breakpoint
DROP TABLE `network_houses`;--> statement-breakpoint
DROP TABLE `notification_preferences`;--> statement-breakpoint
DROP TABLE `notifications`;--> statement-breakpoint
DROP TABLE `parcels`;--> statement-breakpoint
DROP TABLE `protected_lineage`;--> statement-breakpoint
DROP TABLE `requests`;--> statement-breakpoint
DROP TABLE `risks`;--> statement-breakpoint
DROP TABLE `scheduled_bot_tasks`;--> statement-breakpoint
DROP TABLE `scroll_activations`;--> statement-breakpoint
DROP TABLE `scroll_seal_status`;--> statement-breakpoint
DROP TABLE `secure_documents`;--> statement-breakpoint
DROP TABLE `social_media_integrations`;--> statement-breakpoint
DROP TABLE `social_media_posts`;--> statement-breakpoint
DROP TABLE `sovereign_scrolls`;--> statement-breakpoint
DROP TABLE `spark_tokens`;--> statement-breakpoint
DROP TABLE `student_profiles`;--> statement-breakpoint
DROP TABLE `student_progress`;--> statement-breakpoint
DROP TABLE `succession_events`;--> statement-breakpoint
DROP TABLE `sync_cycles`;--> statement-breakpoint
DROP TABLE `system_audit_log`;--> statement-breakpoint
DROP TABLE `token_activation_attempts`;--> statement-breakpoint
DROP TABLE `token_chain_states`;--> statement-breakpoint
DROP TABLE `token_expansions`;--> statement-breakpoint
DROP TABLE `token_locks`;--> statement-breakpoint
DROP TABLE `treasury_claims`;--> statement-breakpoint
DROP TABLE `trust_distribution_contracts`;--> statement-breakpoint
ALTER TABLE `crypto_wallets` MODIFY COLUMN `walletType` enum('bitcoin','ethereum','solana','other') NOT NULL;--> statement-breakpoint
ALTER TABLE `crypto_wallets` DROP COLUMN `businessEntityId`;--> statement-breakpoint
ALTER TABLE `crypto_wallets` DROP COLUMN `walletName`;--> statement-breakpoint
ALTER TABLE `crypto_wallets` DROP COLUMN `privateKeyHash`;