DROP TABLE `academy_courses`;--> statement-breakpoint
DROP TABLE `academy_houses`;--> statement-breakpoint
DROP TABLE `academy_instructors`;--> statement-breakpoint
DROP TABLE `academy_languages`;--> statement-breakpoint
DROP TABLE `academy_lessons`;--> statement-breakpoint
DROP TABLE `accreditation_records`;--> statement-breakpoint
DROP TABLE `ach_batches`;--> statement-breakpoint
DROP TABLE `ach_entries`;--> statement-breakpoint
DROP TABLE `achievement_blockchain_records`;--> statement-breakpoint
DROP TABLE `achievements`;--> statement-breakpoint
DROP TABLE `activation_credits`;--> statement-breakpoint
DROP TABLE `activation_requirements`;--> statement-breakpoint
DROP TABLE `activity_audit_trail`;--> statement-breakpoint
DROP TABLE `ad_placements`;--> statement-breakpoint
DROP TABLE `agent_actions`;--> statement-breakpoint
DROP TABLE `agent_conversations`;--> statement-breakpoint
DROP TABLE `agent_messages`;--> statement-breakpoint
DROP TABLE `agents`;--> statement-breakpoint
DROP TABLE `alert_escalation_rules`;--> statement-breakpoint
DROP TABLE `allocation_pots`;--> statement-breakpoint
DROP TABLE `allocation_transactions`;--> statement-breakpoint
DROP TABLE `app_versions`;--> statement-breakpoint
DROP TABLE `application_activity_log`;--> statement-breakpoint
DROP TABLE `application_documents`;--> statement-breakpoint
DROP TABLE `approvals`;--> statement-breakpoint
DROP TABLE `article_assignments`;--> statement-breakpoint
DROP TABLE `article_reading_progress`;--> statement-breakpoint
DROP TABLE `articles`;--> statement-breakpoint
DROP TABLE `artist_revenue_streams`;--> statement-breakpoint
DROP TABLE `artist_training_progress`;--> statement-breakpoint
DROP TABLE `asset_allocations`;--> statement-breakpoint
DROP TABLE `assets`;--> statement-breakpoint
DROP TABLE `audit_events`;--> statement-breakpoint
DROP TABLE `audit_requests`;--> statement-breakpoint
DROP TABLE `automation_rules`;--> statement-breakpoint
DROP TABLE `autonomous_operations`;--> statement-breakpoint
DROP TABLE `avatar_profiles`;--> statement-breakpoint
DROP TABLE `biometric_credentials`;--> statement-breakpoint
DROP TABLE `blockchain_networks`;--> statement-breakpoint
DROP TABLE `board_meeting_attendance`;--> statement-breakpoint
DROP TABLE `board_members`;--> statement-breakpoint
DROP TABLE `board_positions`;--> statement-breakpoint
DROP TABLE `board_resolution_votes`;--> statement-breakpoint
DROP TABLE `book_annotations`;--> statement-breakpoint
DROP TABLE `book_discussions`;--> statement-breakpoint
DROP TABLE `brain_approvals`;--> statement-breakpoint
DROP TABLE `brain_audit_log`;--> statement-breakpoint
DROP TABLE `brain_permissions`;--> statement-breakpoint
DROP TABLE `brain_recommendations`;--> statement-breakpoint
DROP TABLE `broadcast_analytics`;--> statement-breakpoint
DROP TABLE `broadcast_channel_follows`;--> statement-breakpoint
DROP TABLE `broadcast_channels`;--> statement-breakpoint
DROP TABLE `broadcast_episodes`;--> statement-breakpoint
DROP TABLE `broadcast_listeners`;--> statement-breakpoint
DROP TABLE `broadcast_notifications`;--> statement-breakpoint
DROP TABLE `broadcast_playback_history`;--> statement-breakpoint
DROP TABLE `broadcast_radio_channels`;--> statement-breakpoint
DROP TABLE `broadcast_schedules`;--> statement-breakpoint
DROP TABLE `business_plan_sections`;--> statement-breakpoint
DROP TABLE `business_plans`;--> statement-breakpoint
DROP TABLE `business_positions`;--> statement-breakpoint
DROP TABLE `calendar_events`;--> statement-breakpoint
DROP TABLE `career_interest_submissions`;--> statement-breakpoint
DROP TABLE `champion_nfts`;--> statement-breakpoint
DROP TABLE `change_orders`;--> statement-breakpoint
DROP TABLE `changelog_entries`;--> statement-breakpoint
DROP TABLE `changelog_user_views`;--> statement-breakpoint
DROP TABLE `charge_code_budgets`;--> statement-breakpoint
DROP TABLE `charge_codes`;--> statement-breakpoint
DROP TABLE `chat_attachments`;--> statement-breakpoint
DROP TABLE `chat_messages`;--> statement-breakpoint
DROP TABLE `chat_participants`;--> statement-breakpoint
DROP TABLE `chats`;--> statement-breakpoint
DROP TABLE `community_funds`;--> statement-breakpoint
DROP TABLE `company_users`;--> statement-breakpoint
DROP TABLE `compliance_alerts`;--> statement-breakpoint
DROP TABLE `compliance_tasks`;--> statement-breakpoint
DROP TABLE `comprehension_quizzes`;--> statement-breakpoint
DROP TABLE `consulting_bookings`;--> statement-breakpoint
DROP TABLE `contact_submissions`;--> statement-breakpoint
DROP TABLE `contract_amendments`;--> statement-breakpoint
DROP TABLE `contract_milestones`;--> statement-breakpoint
DROP TABLE `contract_negotiations`;--> statement-breakpoint
DROP TABLE `contract_templates`;--> statement-breakpoint
DROP TABLE `contractor_businesses`;--> statement-breakpoint
DROP TABLE `contractor_invoices`;--> statement-breakpoint
DROP TABLE `contractor_transitions`;--> statement-breakpoint
DROP TABLE `contracts`;--> statement-breakpoint
DROP TABLE `course_completion_certificates`;--> statement-breakpoint
DROP TABLE `course_completions`;--> statement-breakpoint
DROP TABLE `course_progress`;--> statement-breakpoint
DROP TABLE `course_purchases`;--> statement-breakpoint
DROP TABLE `course_recommendations`;--> statement-breakpoint
DROP TABLE `courses`;--> statement-breakpoint
DROP TABLE `creative_artists`;--> statement-breakpoint
DROP TABLE `creative_bookings`;--> statement-breakpoint
DROP TABLE `creative_productions`;--> statement-breakpoint
DROP TABLE `creative_training_programs`;--> statement-breakpoint
DROP TABLE `credential_achievements`;--> statement-breakpoint
DROP TABLE `crypto_transactions`;--> statement-breakpoint
DROP TABLE `crypto_wallets`;--> statement-breakpoint
DROP TABLE `curriculum_projects`;--> statement-breakpoint
DROP TABLE `curriculum_subjects`;--> statement-breakpoint
DROP TABLE `customer_subscriptions`;--> statement-breakpoint
DROP TABLE `delegation_escalations`;--> statement-breakpoint
DROP TABLE `delegation_history`;--> statement-breakpoint
DROP TABLE `deliverable_quality_scores`;--> statement-breakpoint
DROP TABLE `demo_mode_sessions`;--> statement-breakpoint
DROP TABLE `department_simulator_progress`;--> statement-breakpoint
DROP TABLE `departments`;--> statement-breakpoint
DROP TABLE `design_assets`;--> statement-breakpoint
DROP TABLE `design_projects`;--> statement-breakpoint
DROP TABLE `digital_avatars`;--> statement-breakpoint
DROP TABLE `distribution_events`;--> statement-breakpoint
DROP TABLE `distribution_rules`;--> statement-breakpoint
DROP TABLE `dividend_income`;--> statement-breakpoint
DROP TABLE `divine_stem_modules`;--> statement-breakpoint
DROP TABLE `document_access`;--> statement-breakpoint
DROP TABLE `document_access_log`;--> statement-breakpoint
DROP TABLE `document_field_definitions`;--> statement-breakpoint
DROP TABLE `document_folders`;--> statement-breakpoint
DROP TABLE `document_requirements`;--> statement-breakpoint
DROP TABLE `document_templates`;--> statement-breakpoint
DROP TABLE `document_versions`;--> statement-breakpoint
DROP TABLE `document_workflow`;--> statement-breakpoint
DROP TABLE `economic_health_indicators`;--> statement-breakpoint
DROP TABLE `electronic_signatures`;--> statement-breakpoint
DROP TABLE `email_sends`;--> statement-breakpoint
DROP TABLE `email_templates`;--> statement-breakpoint
DROP TABLE `employee_game_sessions`;--> statement-breakpoint
DROP TABLE `employee_onboarding`;--> statement-breakpoint
DROP TABLE `employees`;--> statement-breakpoint
DROP TABLE `employer_tax_forms`;--> statement-breakpoint
DROP TABLE `employment_documents`;--> statement-breakpoint
DROP TABLE `entity_lifecycle_stages`;--> statement-breakpoint
DROP TABLE `episode_interactions`;--> statement-breakpoint
DROP TABLE `estimated_taxes`;--> statement-breakpoint
DROP TABLE `event_invitees`;--> statement-breakpoint
DROP TABLE `excellence_badges`;--> statement-breakpoint
DROP TABLE `exchange_rates`;--> statement-breakpoint
DROP TABLE `external_businesses`;--> statement-breakpoint
DROP TABLE `external_companies`;--> statement-breakpoint
DROP TABLE `facility_plans`;--> statement-breakpoint
DROP TABLE `family_resumes`;--> statement-breakpoint
DROP TABLE `feature_flags`;--> statement-breakpoint
DROP TABLE `feedback_requests`;--> statement-breakpoint
DROP TABLE `filing_reminders`;--> statement-breakpoint
DROP TABLE `filing_tasks`;--> statement-breakpoint
DROP TABLE `filing_workflows`;--> statement-breakpoint
DROP TABLE `financial_errors`;--> statement-breakpoint
DROP TABLE `flame_lock_codes`;--> statement-breakpoint
DROP TABLE `foreign_bank_accounts`;--> statement-breakpoint
DROP TABLE `foreign_entities`;--> statement-breakpoint
DROP TABLE `founder_consulting_engagements`;--> statement-breakpoint
DROP TABLE `founder_income_streams`;--> statement-breakpoint
DROP TABLE `founder_income_summary`;--> statement-breakpoint
DROP TABLE `founder_ip_licenses`;--> statement-breakpoint
DROP TABLE `founder_token_earnings`;--> statement-breakpoint
DROP TABLE `founding_members`;--> statement-breakpoint
DROP TABLE `fraud_flags`;--> statement-breakpoint
DROP TABLE `fund_contributions`;--> statement-breakpoint
DROP TABLE `fund_disbursements`;--> statement-breakpoint
DROP TABLE `funding_sources`;--> statement-breakpoint
DROP TABLE `game_achievements`;--> statement-breakpoint
DROP TABLE `game_center_games`;--> statement-breakpoint
DROP TABLE `game_challenges`;--> statement-breakpoint
DROP TABLE `game_matches`;--> statement-breakpoint
DROP TABLE `game_player_achievements`;--> statement-breakpoint
DROP TABLE `game_player_challenges`;--> statement-breakpoint
DROP TABLE `game_player_stats`;--> statement-breakpoint
DROP TABLE `game_save_states`;--> statement-breakpoint
DROP TABLE `game_scores`;--> statement-breakpoint
DROP TABLE `game_sessions`;--> statement-breakpoint
DROP TABLE `game_tournaments`;--> statement-breakpoint
DROP TABLE `gaming_compliance_reports`;--> statement-breakpoint
DROP TABLE `gaming_leaderboards`;--> statement-breakpoint
DROP TABLE `generated_curriculum`;--> statement-breakpoint
DROP TABLE `generated_documents`;--> statement-breakpoint
DROP TABLE `gift_activation_attempts`;--> statement-breakpoint
DROP TABLE `gift_sale_ratios`;--> statement-breakpoint
DROP TABLE `gift_tokens`;--> statement-breakpoint
DROP TABLE `government_action_notifications`;--> statement-breakpoint
DROP TABLE `government_action_tasks`;--> statement-breakpoint
DROP TABLE `government_actions`;--> statement-breakpoint
DROP TABLE `government_agencies`;--> statement-breakpoint
DROP TABLE `grant_application_documents`;--> statement-breakpoint
DROP TABLE `grant_application_history`;--> statement-breakpoint
DROP TABLE `grant_applications`;--> statement-breakpoint
DROP TABLE `grant_documents`;--> statement-breakpoint
DROP TABLE `grant_funders`;--> statement-breakpoint
DROP TABLE `grant_opportunities`;--> statement-breakpoint
DROP TABLE `grant_tasks`;--> statement-breakpoint
DROP TABLE `guardian_access`;--> statement-breakpoint
DROP TABLE `heir_accumulation_accounts`;--> statement-breakpoint
DROP TABLE `heir_distribution_locks`;--> statement-breakpoint
DROP TABLE `heir_distributions`;--> statement-breakpoint
DROP TABLE `heir_education_benefits`;--> statement-breakpoint
DROP TABLE `heir_vesting_schedules`;--> statement-breakpoint
DROP TABLE `holdings`;--> statement-breakpoint
DROP TABLE `homeschool_portfolios`;--> statement-breakpoint
DROP TABLE `house_activation_events`;--> statement-breakpoint
DROP TABLE `house_activation_progress`;--> statement-breakpoint
DROP TABLE `house_businesses`;--> statement-breakpoint
DROP TABLE `house_contracts`;--> statement-breakpoint
DROP TABLE `house_document_vaults`;--> statement-breakpoint
DROP TABLE `house_heirs`;--> statement-breakpoint
DROP TABLE `house_ledger_transactions`;--> statement-breakpoint
DROP TABLE `house_ledgers`;--> statement-breakpoint
DROP TABLE `house_members`;--> statement-breakpoint
DROP TABLE `house_projected_distributions`;--> statement-breakpoint
DROP TABLE `house_referrals`;--> statement-breakpoint
DROP TABLE `house_service_permissions`;--> statement-breakpoint
DROP TABLE `house_sub_entities`;--> statement-breakpoint
DROP TABLE `house_succession_designations`;--> statement-breakpoint
DROP TABLE `house_templates`;--> statement-breakpoint
DROP TABLE `houses`;--> statement-breakpoint
DROP TABLE `impact_metrics`;--> statement-breakpoint
DROP TABLE `incidents`;--> statement-breakpoint
DROP TABLE `income_events`;--> statement-breakpoint
DROP TABLE `inflow_capture`;--> statement-breakpoint
DROP TABLE `inheritance_queue`;--> statement-breakpoint
DROP TABLE `integrity_triggers`;--> statement-breakpoint
DROP TABLE `international_compliance_filings`;--> statement-breakpoint
DROP TABLE `international_jurisdictions`;--> statement-breakpoint
DROP TABLE `international_trusts`;--> statement-breakpoint
DROP TABLE `investment_alerts`;--> statement-breakpoint
DROP TABLE `investment_goals`;--> statement-breakpoint
DROP TABLE `investment_portfolios`;--> statement-breakpoint
DROP TABLE `investment_transactions`;--> statement-breakpoint
DROP TABLE `invoice_line_items`;--> statement-breakpoint
DROP TABLE `iptv_channel_follows`;--> statement-breakpoint
DROP TABLE `iptv_channels`;--> statement-breakpoint
DROP TABLE `iptv_epg_schedule`;--> statement-breakpoint
DROP TABLE `iptv_playback_history`;--> statement-breakpoint
DROP TABLE `iptv_playlist_items`;--> statement-breakpoint
DROP TABLE `iptv_playlists`;--> statement-breakpoint
DROP TABLE `iptv_recordings`;--> statement-breakpoint
DROP TABLE `iptv_stream_quality_profiles`;--> statement-breakpoint
DROP TABLE `iptv_streams`;--> statement-breakpoint
DROP TABLE `iptv_vod_content`;--> statement-breakpoint
DROP TABLE `job_applications`;--> statement-breakpoint
DROP TABLE `jurisdictions`;--> statement-breakpoint
DROP TABLE `landing_page_analytics`;--> statement-breakpoint
DROP TABLE `language_lessons`;--> statement-breakpoint
DROP TABLE `learning_pathways`;--> statement-breakpoint
DROP TABLE `ledger_access_logs`;--> statement-breakpoint
DROP TABLE `library_books`;--> statement-breakpoint
DROP TABLE `lifecycle_events`;--> statement-breakpoint
DROP TABLE `live_broadcasts`;--> statement-breakpoint
DROP TABLE `living_scrolls`;--> statement-breakpoint
DROP TABLE `luvchain_blocks`;--> statement-breakpoint
DROP TABLE `luvchain_smart_contracts`;--> statement-breakpoint
DROP TABLE `luvchain_transactions`;--> statement-breakpoint
DROP TABLE `main_house_ledger`;--> statement-breakpoint
DROP TABLE `market_data`;--> statement-breakpoint
DROP TABLE `mastery_certificates`;--> statement-breakpoint
DROP TABLE `matchmaking_queue`;--> statement-breakpoint
DROP TABLE `meeting_attendance`;--> statement-breakpoint
DROP TABLE `meeting_chats`;--> statement-breakpoint
DROP TABLE `meeting_participants`;--> statement-breakpoint
DROP TABLE `meeting_reminders`;--> statement-breakpoint
DROP TABLE `meetings`;--> statement-breakpoint
DROP TABLE `member_credentials`;--> statement-breakpoint
DROP TABLE `metrics`;--> statement-breakpoint
DROP TABLE `mirror_tokens`;--> statement-breakpoint
DROP TABLE `multi_chain_crypto_transactions`;--> statement-breakpoint
DROP TABLE `multi_chain_wallets`;--> statement-breakpoint
DROP TABLE `negotiation_history`;--> statement-breakpoint
DROP TABLE `negotiation_playbooks`;--> statement-breakpoint
DROP TABLE `network_houses`;--> statement-breakpoint
DROP TABLE `nft_mint_queue`;--> statement-breakpoint
DROP TABLE `notification_logs`;--> statement-breakpoint
DROP TABLE `notification_preferences`;--> statement-breakpoint
DROP TABLE `notifications`;--> statement-breakpoint
DROP TABLE `offer_package_documents`;--> statement-breakpoint
DROP TABLE `offer_packages`;--> statement-breakpoint
DROP TABLE `office_document_collaborators`;--> statement-breakpoint
DROP TABLE `office_document_comments`;--> statement-breakpoint
DROP TABLE `office_document_signatures`;--> statement-breakpoint
DROP TABLE `office_document_templates`;--> statement-breakpoint
DROP TABLE `office_document_versions`;--> statement-breakpoint
DROP TABLE `office_documents`;--> statement-breakpoint
DROP TABLE `onboarding_assessments`;--> statement-breakpoint
DROP TABLE `onboarding_checklist_items`;--> statement-breakpoint
DROP TABLE `onboarding_checklists`;--> statement-breakpoint
DROP TABLE `onboarding_house_setup`;--> statement-breakpoint
DROP TABLE `onboarding_journeys`;--> statement-breakpoint
DROP TABLE `onboarding_progress`;--> statement-breakpoint
DROP TABLE `onboarding_questions`;--> statement-breakpoint
DROP TABLE `onboarding_responses`;--> statement-breakpoint
DROP TABLE `onboarding_task_progress`;--> statement-breakpoint
DROP TABLE `online_course_details`;--> statement-breakpoint
DROP TABLE `operating_procedures`;--> statement-breakpoint
DROP TABLE `parcels`;--> statement-breakpoint
DROP TABLE `payment_fulfillments`;--> statement-breakpoint
DROP TABLE `payment_requests`;--> statement-breakpoint
DROP TABLE `payroll_periods`;--> statement-breakpoint
DROP TABLE `payroll_records`;--> statement-breakpoint
DROP TABLE `payroll_runs`;--> statement-breakpoint
DROP TABLE `pdf_operations`;--> statement-breakpoint
DROP TABLE `peer_feedback`;--> statement-breakpoint
DROP TABLE `pending_heir_placeholders`;--> statement-breakpoint
DROP TABLE `pending_house_heirs`;--> statement-breakpoint
DROP TABLE `performance_goals`;--> statement-breakpoint
DROP TABLE `performance_reports`;--> statement-breakpoint
DROP TABLE `performance_reviews`;--> statement-breakpoint
DROP TABLE `placement_assessment_questions`;--> statement-breakpoint
DROP TABLE `placement_assessment_responses`;--> statement-breakpoint
DROP TABLE `platform_services_agreements`;--> statement-breakpoint
DROP TABLE `platform_subscription_plans`;--> statement-breakpoint
DROP TABLE `platform_usage_fees`;--> statement-breakpoint
DROP TABLE `podcast_episodes`;--> statement-breakpoint
DROP TABLE `position_holders`;--> statement-breakpoint
DROP TABLE `position_requisitions`;--> statement-breakpoint
DROP TABLE `price_history`;--> statement-breakpoint
DROP TABLE `procedure_acknowledgments`;--> statement-breakpoint
DROP TABLE `procedure_categories`;--> statement-breakpoint
DROP TABLE `production_credits`;--> statement-breakpoint
DROP TABLE `progression_events`;--> statement-breakpoint
DROP TABLE `progression_milestones`;--> statement-breakpoint
DROP TABLE `project_budget_items`;--> statement-breakpoint
DROP TABLE `project_milestones`;--> statement-breakpoint
DROP TABLE `project_risks`;--> statement-breakpoint
DROP TABLE `project_status_reports`;--> statement-breakpoint
DROP TABLE `project_tasks`;--> statement-breakpoint
DROP TABLE `projects`;--> statement-breakpoint
DROP TABLE `properties`;--> statement-breakpoint
DROP TABLE `property_acquisitions`;--> statement-breakpoint
DROP TABLE `property_documents`;--> statement-breakpoint
DROP TABLE `property_expenses`;--> statement-breakpoint
DROP TABLE `property_financials`;--> statement-breakpoint
DROP TABLE `property_income`;--> statement-breakpoint
DROP TABLE `property_inspections`;--> statement-breakpoint
DROP TABLE `property_maintenance_logs`;--> statement-breakpoint
DROP TABLE `property_project_expenses`;--> statement-breakpoint
DROP TABLE `property_project_milestones`;--> statement-breakpoint
DROP TABLE `property_project_tasks`;--> statement-breakpoint
DROP TABLE `property_projects`;--> statement-breakpoint
DROP TABLE `property_tenants`;--> statement-breakpoint
DROP TABLE `property_utilities`;--> statement-breakpoint
DROP TABLE `property_valuations`;--> statement-breakpoint
DROP TABLE `property_vendors`;--> statement-breakpoint
DROP TABLE `protected_lineage`;--> statement-breakpoint
DROP TABLE `purchase_request_comments`;--> statement-breakpoint
DROP TABLE `purchase_requests`;--> statement-breakpoint
DROP TABLE `purchased_course_progress`;--> statement-breakpoint
DROP TABLE `quality_standards`;--> statement-breakpoint
DROP TABLE `quiz_attempts`;--> statement-breakpoint
DROP TABLE `reading_acknowledgments`;--> statement-breakpoint
DROP TABLE `reading_certificates`;--> statement-breakpoint
DROP TABLE `reading_compliance_reports`;--> statement-breakpoint
DROP TABLE `reading_discussion_requirements`;--> statement-breakpoint
DROP TABLE `reading_sessions`;--> statement-breakpoint
DROP TABLE `reading_streaks`;--> statement-breakpoint
DROP TABLE `real_estate_agents`;--> statement-breakpoint
DROP TABLE `real_estate_properties`;--> statement-breakpoint
DROP TABLE `requests`;--> statement-breakpoint
DROP TABLE `required_readings`;--> statement-breakpoint
DROP TABLE `resource_link_categories`;--> statement-breakpoint
DROP TABLE `resource_links`;--> statement-breakpoint
DROP TABLE `restoration_cases`;--> statement-breakpoint
DROP TABLE `revenue_sharing_events`;--> statement-breakpoint
DROP TABLE `risks`;--> statement-breakpoint
DROP TABLE `sandbox_entities`;--> statement-breakpoint
DROP TABLE `sandbox_operations`;--> statement-breakpoint
DROP TABLE `sandbox_sessions`;--> statement-breakpoint
DROP TABLE `sandbox_snapshots`;--> statement-breakpoint
DROP TABLE `sandbox_templates`;--> statement-breakpoint
DROP TABLE `sandbox_transactions`;--> statement-breakpoint
DROP TABLE `scheduled_agent_tasks`;--> statement-breakpoint
DROP TABLE `scheduled_compliance_checks`;--> statement-breakpoint
DROP TABLE `scholarship_applications`;--> statement-breakpoint
DROP TABLE `scholarship_fund`;--> statement-breakpoint
DROP TABLE `scholarship_fund_transactions`;--> statement-breakpoint
DROP TABLE `scholarship_programs`;--> statement-breakpoint
DROP TABLE `scroll_activations`;--> statement-breakpoint
DROP TABLE `scroll_seal_status`;--> statement-breakpoint
DROP TABLE `secure_documents`;--> statement-breakpoint
DROP TABLE `service_availability`;--> statement-breakpoint
DROP TABLE `service_bookings`;--> statement-breakpoint
DROP TABLE `service_catalog`;--> statement-breakpoint
DROP TABLE `service_categories`;--> statement-breakpoint
DROP TABLE `service_integrations`;--> statement-breakpoint
DROP TABLE `service_offerings`;--> statement-breakpoint
DROP TABLE `service_orders`;--> statement-breakpoint
DROP TABLE `service_subscriptions`;--> statement-breakpoint
DROP TABLE `signature_audit_log`;--> statement-breakpoint
DROP TABLE `signature_request_signers`;--> statement-breakpoint
DROP TABLE `signature_requests`;--> statement-breakpoint
DROP TABLE `signatures`;--> statement-breakpoint
DROP TABLE `simulator_certificates`;--> statement-breakpoint
DROP TABLE `simulator_completions`;--> statement-breakpoint
DROP TABLE `skill_certifications`;--> statement-breakpoint
DROP TABLE `skill_taxonomy`;--> statement-breakpoint
DROP TABLE `sme_contributors`;--> statement-breakpoint
DROP TABLE `social_media_integrations`;--> statement-breakpoint
DROP TABLE `social_media_posts`;--> statement-breakpoint
DROP TABLE `software_license_assignments`;--> statement-breakpoint
DROP TABLE `software_license_categories`;--> statement-breakpoint
DROP TABLE `software_licenses`;--> statement-breakpoint
DROP TABLE `software_vendor_contracts`;--> statement-breakpoint
DROP TABLE `sovereign_scrolls`;--> statement-breakpoint
DROP TABLE `spark_tokens`;--> statement-breakpoint
DROP TABLE `specialist_maturity_assessments`;--> statement-breakpoint
DROP TABLE `specialist_milestones`;--> statement-breakpoint
DROP TABLE `specialist_tracks`;--> statement-breakpoint
DROP TABLE `spectator_sessions`;--> statement-breakpoint
DROP TABLE `spendthrift_provisions`;--> statement-breakpoint
DROP TABLE `split_change_request_comments`;--> statement-breakpoint
DROP TABLE `split_change_requests`;--> statement-breakpoint
DROP TABLE `split_configuration_history`;--> statement-breakpoint
DROP TABLE `sponsorships`;--> statement-breakpoint
DROP TABLE `staff_members`;--> statement-breakpoint
DROP TABLE `statements_of_work`;--> statement-breakpoint
DROP TABLE `stock_alerts`;--> statement-breakpoint
DROP TABLE `stock_events`;--> statement-breakpoint
DROP TABLE `stock_price_history`;--> statement-breakpoint
DROP TABLE `stock_watchlist`;--> statement-breakpoint
DROP TABLE `streak_notifications`;--> statement-breakpoint
DROP TABLE `student_enrollments`;--> statement-breakpoint
DROP TABLE `student_placement_assessments`;--> statement-breakpoint
DROP TABLE `student_profiles`;--> statement-breakpoint
DROP TABLE `student_progress`;--> statement-breakpoint
DROP TABLE `subscription_plans`;--> statement-breakpoint
DROP TABLE `succession_events`;--> statement-breakpoint
DROP TABLE `supported_locales`;--> statement-breakpoint
DROP TABLE `supported_tokens`;--> statement-breakpoint
DROP TABLE `swal_nft_transfers`;--> statement-breakpoint
DROP TABLE `swal_nfts`;--> statement-breakpoint
DROP TABLE `swal_purchases`;--> statement-breakpoint
DROP TABLE `swal_royalty_distributions`;--> statement-breakpoint
DROP TABLE `swal_token_supply`;--> statement-breakpoint
DROP TABLE `swal_tokens`;--> statement-breakpoint
DROP TABLE `swal_unlocks`;--> statement-breakpoint
DROP TABLE `swal_user_progress`;--> statement-breakpoint
DROP TABLE `swot_analyses`;--> statement-breakpoint
DROP TABLE `swot_items`;--> statement-breakpoint
DROP TABLE `sync_cycles`;--> statement-breakpoint
DROP TABLE `sync_queue`;--> statement-breakpoint
DROP TABLE `system_audit_log`;--> statement-breakpoint
DROP TABLE `system_job_configurations`;--> statement-breakpoint
DROP TABLE `system_job_executions`;--> statement-breakpoint
DROP TABLE `system_versions`;--> statement-breakpoint
DROP TABLE `tax_deductions`;--> statement-breakpoint
DROP TABLE `tax_documents`;--> statement-breakpoint
DROP TABLE `tax_filings`;--> statement-breakpoint
DROP TABLE `tax_treaties`;--> statement-breakpoint
DROP TABLE `tax_years`;--> statement-breakpoint
DROP TABLE `team_event_participants`;--> statement-breakpoint
DROP TABLE `team_game_events`;--> statement-breakpoint
DROP TABLE `time_entries`;--> statement-breakpoint
DROP TABLE `time_off_requests`;--> statement-breakpoint
DROP TABLE `timekeeping_workers`;--> statement-breakpoint
DROP TABLE `timesheet_approvals`;--> statement-breakpoint
DROP TABLE `timesheets`;--> statement-breakpoint
DROP TABLE `token_accounts`;--> statement-breakpoint
DROP TABLE `token_activation_attempts`;--> statement-breakpoint
DROP TABLE `token_chain_states`;--> statement-breakpoint
DROP TABLE `token_expansions`;--> statement-breakpoint
DROP TABLE `token_locks`;--> statement-breakpoint
DROP TABLE `token_transaction_log`;--> statement-breakpoint
DROP TABLE `token_transactions`;--> statement-breakpoint
DROP TABLE `tournament_matches`;--> statement-breakpoint
DROP TABLE `tournament_participants`;--> statement-breakpoint
DROP TABLE `trademark_searches`;--> statement-breakpoint
DROP TABLE `training_answers`;--> statement-breakpoint
DROP TABLE `training_hub_assignments`;--> statement-breakpoint
DROP TABLE `training_hub_certifications`;--> statement-breakpoint
DROP TABLE `training_hub_modules`;--> statement-breakpoint
DROP TABLE `training_hub_progress`;--> statement-breakpoint
DROP TABLE `training_hub_scenarios`;--> statement-breakpoint
DROP TABLE `training_modules`;--> statement-breakpoint
DROP TABLE `training_questions`;--> statement-breakpoint
DROP TABLE `training_responses`;--> statement-breakpoint
DROP TABLE `training_sessions`;--> statement-breakpoint
DROP TABLE `training_topics`;--> statement-breakpoint
DROP TABLE `translation_contributors`;--> statement-breakpoint
DROP TABLE `translation_suggestions`;--> statement-breakpoint
DROP TABLE `translation_votes`;--> statement-breakpoint
DROP TABLE `treasury_claims`;--> statement-breakpoint
DROP TABLE `trial_exit_surveys`;--> statement-breakpoint
DROP TABLE `trial_feature_exploration`;--> statement-breakpoint
DROP TABLE `trial_feedback`;--> statement-breakpoint
DROP TABLE `trial_page_views`;--> statement-breakpoint
DROP TABLE `trial_sample_data`;--> statement-breakpoint
DROP TABLE `trial_sessions`;--> statement-breakpoint
DROP TABLE `trial_users`;--> statement-breakpoint
DROP TABLE `trivia_categories`;--> statement-breakpoint
DROP TABLE `trivia_questions`;--> statement-breakpoint
DROP TABLE `trust_distribution_contracts`;--> statement-breakpoint
DROP TABLE `user_content_access`;--> statement-breakpoint
DROP TABLE `user_preferences`;--> statement-breakpoint
DROP TABLE `user_presence`;--> statement-breakpoint
DROP TABLE `user_profiles`;--> statement-breakpoint
DROP TABLE `user_token_balance`;--> statement-breakpoint
DROP TABLE `vault_access_logs`;--> statement-breakpoint
DROP TABLE `vault_documents`;--> statement-breakpoint
DROP TABLE `vault_folders`;--> statement-breakpoint
DROP TABLE `video_provider_configs`;--> statement-breakpoint
DROP TABLE `virtual_spaces`;--> statement-breakpoint
DROP TABLE `vocabulary_words`;--> statement-breakpoint
DROP TABLE `vod_episodes`;--> statement-breakpoint
DROP TABLE `vod_movies`;--> statement-breakpoint
DROP TABLE `vod_reviews`;--> statement-breakpoint
DROP TABLE `vod_series`;--> statement-breakpoint
DROP TABLE `vod_viewing_history`;--> statement-breakpoint
DROP TABLE `vod_watchlist`;--> statement-breakpoint
DROP TABLE `w2_workers`;--> statement-breakpoint
DROP TABLE `waitlist_signups`;--> statement-breakpoint
DROP TABLE `wallet_balances`;--> statement-breakpoint
DROP TABLE `watchlist_items`;--> statement-breakpoint
DROP TABLE `weekly_game_requirements`;--> statement-breakpoint
DROP TABLE `worker_badges`;--> statement-breakpoint
DROP TABLE `worker_bank_accounts`;--> statement-breakpoint
DROP TABLE `worker_certifications`;--> statement-breakpoint
DROP TABLE `worker_charge_code_assignments`;--> statement-breakpoint
DROP TABLE `worker_learning_progress`;--> statement-breakpoint
DROP TABLE `worker_milestone_progress`;--> statement-breakpoint
DROP TABLE `worker_progressions`;--> statement-breakpoint
DROP TABLE `worker_skills`;--> statement-breakpoint
DROP TABLE `worker_tax_withholdings`;--> statement-breakpoint
DROP TABLE `workflow_template_ratings`;--> statement-breakpoint
DROP TABLE `workflow_template_usage`;--> statement-breakpoint
DROP TABLE `ytd_totals`;--> statement-breakpoint
ALTER TABLE `business_entities` MODIFY COLUMN `entityType` enum('trust','llc','corporation','collective') NOT NULL;--> statement-breakpoint
ALTER TABLE `simulator_sessions` MODIFY COLUMN `simulatorType` enum('business_setup','financial_management','entity_operations') NOT NULL;--> statement-breakpoint
ALTER TABLE `users` MODIFY COLUMN `role` enum('user','admin') NOT NULL DEFAULT 'user';--> statement-breakpoint
ALTER TABLE `business_entities` DROP COLUMN `ein`;--> statement-breakpoint
ALTER TABLE `business_entities` DROP COLUMN `stateOfFormation`;--> statement-breakpoint
ALTER TABLE `business_entities` DROP COLUMN `stateEntityId`;--> statement-breakpoint
ALTER TABLE `business_entities` DROP COLUMN `formationDate`;--> statement-breakpoint
ALTER TABLE `business_entities` DROP COLUMN `registeredAddress`;--> statement-breakpoint
ALTER TABLE `business_entities` DROP COLUMN `physicalAddress`;--> statement-breakpoint
ALTER TABLE `business_entities` DROP COLUMN `houseParticipationStatus`;--> statement-breakpoint
ALTER TABLE `business_entities` DROP COLUMN `linkedHouseId`;--> statement-breakpoint
ALTER TABLE `business_entities` DROP COLUMN `houseActivatedAt`;--> statement-breakpoint
ALTER TABLE `business_entities` DROP COLUMN `houseOptOutReason`;--> statement-breakpoint
ALTER TABLE `business_entities` DROP COLUMN `parentEntityId`;--> statement-breakpoint
ALTER TABLE `business_entities` DROP COLUMN `allocationPercentage`;--> statement-breakpoint
ALTER TABLE `users` DROP COLUMN `passwordHash`;