CREATE TABLE `scroll_seal_status` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` varchar(255) NOT NULL,
	`houseId` int NOT NULL,
	`scrollNumber` int NOT NULL,
	`scrollTitle` varchar(255),
	`isSealed` boolean NOT NULL DEFAULT false,
	`sealedAt` timestamp,
	`sealedBy` varchar(255),
	`sealHash` varchar(64),
	`verificationMethod` enum('manual','automatic','gpt_audit','course_completion') DEFAULT 'manual',
	`courseId` int,
	`moduleId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `scroll_seal_status_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `token_activation_attempts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`houseId` int NOT NULL,
	`userId` varchar(255) NOT NULL,
	`attemptTokenType` enum('mirror','gift','spark','house','crown') NOT NULL,
	`attemptStatus` enum('approved','denied','pending') NOT NULL,
	`expectedToken` varchar(50),
	`scrollsRequired` json DEFAULT ('[]'),
	`scrollsSealed` json DEFAULT ('[]'),
	`scrollsMissing` json DEFAULT ('[]'),
	`resultMessage` text,
	`currentChain` json DEFAULT ('[]'),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `token_activation_attempts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `token_chain_states` (
	`id` int AUTO_INCREMENT NOT NULL,
	`houseId` int NOT NULL,
	`userId` varchar(255) NOT NULL,
	`currentTokenIndex` int NOT NULL DEFAULT 0,
	`activatedTokens` json DEFAULT ('[]'),
	`mirrorActivatedAt` timestamp,
	`giftActivatedAt` timestamp,
	`sparkActivatedAt` timestamp,
	`houseActivatedAt` timestamp,
	`mirrorScrollsSealed` json DEFAULT ('[]'),
	`giftScrollsSealed` json DEFAULT ('[]'),
	`sparkScrollsSealed` json DEFAULT ('[]'),
	`houseScrollsSealed` json DEFAULT ('[]'),
	`chainStatus` enum('pending','in_progress','completed','blocked') NOT NULL DEFAULT 'pending',
	`blockReason` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `token_chain_states_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `token_expansions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sourceTokenId` int NOT NULL,
	`sourceHouseId` int NOT NULL,
	`sourceUserId` varchar(255) NOT NULL,
	`targetHouseId` int,
	`targetUserId` varchar(255),
	`expansionType` enum('bloodline','mirrored','adaptive') NOT NULL,
	`requiredScrollsComplete` boolean NOT NULL DEFAULT false,
	`requiredTimeElapsed` boolean NOT NULL DEFAULT false,
	`minimumDaysRequired` int DEFAULT 365,
	`expansionStatus` enum('pending','approved','rejected','completed','frozen') NOT NULL DEFAULT 'pending',
	`approvedBy` varchar(255),
	`approvedAt` timestamp,
	`rejectionReason` text,
	`enforcementActive` boolean NOT NULL DEFAULT true,
	`enforcementViolations` int NOT NULL DEFAULT 0,
	`frozenAt` timestamp,
	`freezeReason` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `token_expansions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `token_locks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tokenId` int NOT NULL,
	`tokenType` enum('mirror','gift','spark','house','crown') NOT NULL,
	`houseId` int NOT NULL,
	`userId` varchar(255) NOT NULL,
	`lockType` enum('time_based','scroll_based','lineage_based','manual') NOT NULL,
	`lockDurationDays` int,
	`lockStartedAt` timestamp NOT NULL DEFAULT (now()),
	`lockExpiresAt` timestamp,
	`requiredScrolls` json DEFAULT ('[]'),
	`sealedScrolls` json DEFAULT ('[]'),
	`requiresLineageVerification` boolean DEFAULT false,
	`lineageVerifiedAt` timestamp,
	`lineageVerifiedBy` varchar(255),
	`lockStatus` enum('active','unlocked','expired','violated') NOT NULL DEFAULT 'active',
	`unlockedAt` timestamp,
	`unlockReason` text,
	`violationCount` int NOT NULL DEFAULT 0,
	`lastViolationAt` timestamp,
	`violationDetails` json DEFAULT ('[]'),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `token_locks_id` PRIMARY KEY(`id`)
);
