CREATE TABLE `gift_activation_attempts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`giftId` int NOT NULL,
	`userId` varchar(255) NOT NULL,
	`giftAttemptStatus` enum('approved','denied','pending') NOT NULL,
	`anniversaryMet` boolean,
	`scrollsComplete` boolean,
	`lineageVerified` boolean,
	`lockExpired` boolean,
	`resultMessage` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `gift_activation_attempts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `gift_tokens` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sourceUserId` varchar(255) NOT NULL,
	`sourceHouseId` int NOT NULL,
	`targetUserId` varchar(255),
	`targetHouseId` int,
	`targetEmail` varchar(255),
	`targetName` varchar(255),
	`giftType` enum('mirror','adaptive','locked') NOT NULL,
	`giftValue` decimal(20,8),
	`giftDescription` text,
	`giftMessage` text,
	`requiresAnniversary` boolean DEFAULT false,
	`anniversaryDate` timestamp,
	`requiresStewardshipScrolls` boolean DEFAULT false,
	`requiredScrolls` json,
	`lockDurationDays` int,
	`lockExpiresAt` timestamp,
	`requiresLineageVerification` boolean DEFAULT false,
	`lineageVerified` boolean DEFAULT false,
	`lineageVerifiedAt` timestamp,
	`lineageVerifiedBy` varchar(255),
	`giftStatus` enum('pending','awaiting_activation','activated','claimed','expired','revoked') NOT NULL DEFAULT 'pending',
	`activatedAt` timestamp,
	`claimedAt` timestamp,
	`revokedAt` timestamp,
	`revokeReason` text,
	`giftHash` varchar(64),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `gift_tokens_id` PRIMARY KEY(`id`)
);
