CREATE TABLE IF NOT EXISTS `apprenticeship_applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`partnerId` int NOT NULL,
	`programName` varchar(255) NOT NULL,
	`tradeCategory` varchar(100) NOT NULL,
	`ap_app_status` enum('draft','submitted','under_review','interview','accepted','rejected','withdrawn','placed') NOT NULL DEFAULT 'draft',
	`coverLetter` text,
	`resumeUrl` varchar(500),
	`relevantSkills` json,
	`educationLevel` varchar(100),
	`preferredStartDate` timestamp,
	`adminNotes` text,
	`reviewedBy` int,
	`reviewedAt` timestamp,
	`placementStartDate` timestamp,
	`placementEndDate` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `apprenticeship_applications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `apprenticeship_partners` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`description` text,
	`website` varchar(500),
	`contactEmail` varchar(255),
	`contactPhone` varchar(50),
	`logoUrl` varchar(500),
	`industry` varchar(100) NOT NULL,
	`tradeCategories` json,
	`programTypes` json,
	`locations` json,
	`minAge` int DEFAULT 16,
	`maxAge` int DEFAULT 99,
	`durationWeeks` int,
	`isPaid` boolean DEFAULT false,
	`stipendAmount` varchar(100),
	`certificationOffered` boolean DEFAULT false,
	`certificationName` varchar(255),
	`ap_partner_status` enum('active','pending','inactive','archived') NOT NULL DEFAULT 'active',
	`partnerSince` timestamp DEFAULT (now()),
	`notes` text,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `apprenticeship_partners_id` PRIMARY KEY(`id`)
);
