import { useState, useMemo } from "react";
import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  BookOpen,
  Sparkles,
  Loader2,
  CheckCircle2,
  MessageSquare,
  Wand2,
  Eye,
  PenLine,
  Target,
  Clock,
  ChevronRight,
  AlertCircle,
  Plus,
  Lightbulb,
} from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/_core/hooks/useAuth";

const levelBandLabels: Record<string, string> = {
  early_elementary: "K-2",
  upper_elementary: "3-5",
  middle_school: "6-8",
  high_school_intro: "9-10",
  high_school_adv: "11-12",
  certification: "Cert",
};

export default function AcademyK12EducatorReview() {
  const { user } = useAuth();
  const [selectedSubjectId, setSelectedSubjectId] = useState<number | null>(null);
  const [selectedUnitId, setSelectedUnitId] = useState<number | null>(null);
  const [selectedLessonId, setSelectedLessonId] = useState<number | null>(null);
  const [generatingContent, setGeneratingContent] = useState(false);
  const [generatingAssessment, setGeneratingAssessment] = useState(false);
  const [humanNoteContent, setHumanNoteContent] = useState("");
  const [humanNoteType, setHumanNoteType] = useState("cultural_context");
  const [addingNote, setAddingNote] = useState(false);
  const [generatingUnit, setGeneratingUnit] = useState(false);

  // Data queries
  const { data: subjects } = trpc.academyK12.getSubjects.useQuery();
  const { data: units, refetch: refetchUnits } = trpc.academyK12.getUnitsBySubject.useQuery(
    { subjectId: selectedSubjectId! },
    { enabled: !!selectedSubjectId }
  );
  const { data: lessons, refetch: refetchLessons } = trpc.academyK12.getLessonsByUnit.useQuery(
    { unitId: selectedUnitId! },
    { enabled: !!selectedUnitId }
  );
  const { data: lessonDetail, refetch: refetchLesson } = trpc.academyK12.getLessonById.useQuery(
    { id: selectedLessonId! },
    { enabled: !!selectedLessonId }
  );
  const { data: humanNotes, refetch: refetchNotes } = trpc.academyK12.getHumanNotes.useQuery(
    { targetType: "lesson", targetId: selectedLessonId! },
    { enabled: !!selectedLessonId }
  );

  // Mutations
  const generateLesson = trpc.academyK12.generateLessonContent.useMutation({
    onSuccess: () => {
      toast.success("Lesson content generated by AI. Ready for your review.");
      refetchLessons();
      setGeneratingContent(false);
    },
    onError: (err) => {
      toast.error("Failed to generate: " + err.message);
      setGeneratingContent(false);
    },
  });

  const generateAssessment = trpc.academyK12.generateAssessment.useMutation({
    onSuccess: () => {
      toast.success("Assessment generated. Review and customize the questions.");
      setGeneratingAssessment(false);
    },
    onError: (err) => {
      toast.error("Failed to generate assessment: " + err.message);
      setGeneratingAssessment(false);
    },
  });

  const addHumanNote = trpc.academyK12.addHumanNote.useMutation({
    onSuccess: () => {
      toast.success("Educator note added successfully.");
      setHumanNoteContent("");
      setAddingNote(false);
      refetchNotes();
    },
    onError: (err) => {
      toast.error("Failed to add note: " + err.message);
    },
  });

  const reviewContent = trpc.academyK12.reviewContent.useMutation({
    onSuccess: () => {
      toast.success("Content marked as reviewed.");
      refetchLesson();
    },
    onError: (err) => {
      toast.error("Failed to review: " + err.message);
    },
  });

  const publishNote = trpc.academyK12.publishHumanNote.useMutation({
    onSuccess: () => {
      toast.success("Note published — students will now see this perspective.");
      refetchNotes();
    },
  });

  const generateUnitOutline = trpc.academyK12.generateUnitOutline.useMutation({
    onSuccess: (data) => {
      toast.success(`Generated ${data.lessonIds?.length || 0} lesson outlines for this unit.`);
      refetchLessons();
      setGeneratingUnit(false);
    },
    onError: (err) => {
      toast.error("Failed to generate unit outline: " + err.message);
      setGeneratingUnit(false);
    },
  });

  const selectedSubject = useMemo(() => subjects?.find((s: any) => s.id === selectedSubjectId), [subjects, selectedSubjectId]);
  const selectedUnit = useMemo(() => units?.find((u: any) => u.id === selectedUnitId), [units, selectedUnitId]);

  return (
    <DashboardLayout>
      <div className="p-6 max-w-7xl mx-auto">
        {/* Header */}
        <div className="mb-6">
          <div className="flex items-center gap-3 mb-2">
            <div className="p-2 bg-emerald-100 rounded-lg">
              <PenLine className="w-6 h-6 text-emerald-700" />
            </div>
            <div>
              <h1 className="text-2xl font-bold text-foreground">Educator Review & Content Builder</h1>
              <p className="text-sm text-muted-foreground">
                AI generates the framework — you infuse the human perspective, cultural context, and lived experience.
              </p>
            </div>
          </div>
        </div>

        {/* Workflow Explanation */}
        <div className="bg-gradient-to-r from-emerald-50 to-teal-50 dark:from-emerald-950/20 dark:to-teal-950/20 rounded-xl p-5 border border-emerald-200 mb-6">
          <h3 className="font-bold text-foreground mb-2 flex items-center gap-2">
            <Lightbulb className="w-4 h-4 text-emerald-600" />
            Human-AI Collaboration Workflow
          </h3>
          <div className="grid sm:grid-cols-4 gap-3 text-sm">
            <div className="flex items-start gap-2">
              <span className="bg-emerald-200 text-emerald-800 rounded-full w-5 h-5 flex items-center justify-center text-xs font-bold flex-shrink-0">1</span>
              <span className="text-muted-foreground"><strong className="text-foreground">AI Generates</strong> — Standards-aligned lessons and assessments</span>
            </div>
            <div className="flex items-start gap-2">
              <span className="bg-emerald-200 text-emerald-800 rounded-full w-5 h-5 flex items-center justify-center text-xs font-bold flex-shrink-0">2</span>
              <span className="text-muted-foreground"><strong className="text-foreground">You Review</strong> — Check accuracy, add cultural context</span>
            </div>
            <div className="flex items-start gap-2">
              <span className="bg-emerald-200 text-emerald-800 rounded-full w-5 h-5 flex items-center justify-center text-xs font-bold flex-shrink-0">3</span>
              <span className="text-muted-foreground"><strong className="text-foreground">You Enrich</strong> — Add educator notes, real-world stories</span>
            </div>
            <div className="flex items-start gap-2">
              <span className="bg-emerald-200 text-emerald-800 rounded-full w-5 h-5 flex items-center justify-center text-xs font-bold flex-shrink-0">4</span>
              <span className="text-muted-foreground"><strong className="text-foreground">Publish</strong> — Content goes live for students</span>
            </div>
          </div>
        </div>

        {/* Subject / Unit / Lesson Selectors */}
        <div className="grid sm:grid-cols-3 gap-4 mb-6">
          <div>
            <label className="text-sm font-medium text-foreground mb-1 block">Subject</label>
            <Select
              value={selectedSubjectId?.toString() || ""}
              onValueChange={(v) => {
                setSelectedSubjectId(parseInt(v));
                setSelectedUnitId(null);
                setSelectedLessonId(null);
              }}
            >
              <SelectTrigger>
                <SelectValue placeholder="Select a subject" />
              </SelectTrigger>
              <SelectContent>
                {subjects?.map((s: any) => (
                  <SelectItem key={s.id} value={s.id.toString()}>
                    {s.iconEmoji} {s.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div>
            <label className="text-sm font-medium text-foreground mb-1 block">Unit</label>
            <Select
              value={selectedUnitId?.toString() || ""}
              onValueChange={(v) => {
                setSelectedUnitId(parseInt(v));
                setSelectedLessonId(null);
              }}
              disabled={!selectedSubjectId}
            >
              <SelectTrigger>
                <SelectValue placeholder={selectedSubjectId ? "Select a unit" : "Select subject first"} />
              </SelectTrigger>
              <SelectContent>
                {units?.map((u: any) => (
                  <SelectItem key={u.id} value={u.id.toString()}>
                    {u.title} ({levelBandLabels[u.levelBand] || u.levelBand})
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div>
            <label className="text-sm font-medium text-foreground mb-1 block">Lesson</label>
            <Select
              value={selectedLessonId?.toString() || ""}
              onValueChange={(v) => setSelectedLessonId(parseInt(v))}
              disabled={!selectedUnitId}
            >
              <SelectTrigger>
                <SelectValue placeholder={selectedUnitId ? "Select a lesson" : "Select unit first"} />
              </SelectTrigger>
              <SelectContent>
                {lessons?.map((l: any) => (
                  <SelectItem key={l.id} value={l.id.toString()}>
                    {l.title}
                    {l.humanReviewed && " ✓"}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </div>

        {/* AI Generation Actions */}
        {selectedUnitId && (
          <div className="flex flex-wrap gap-3 mb-6">
            <Button
              variant="outline"
              size="sm"
              disabled={generatingUnit}
              onClick={() => {
                if (!selectedUnit || !selectedSubject) return;
                setGeneratingUnit(true);
                generateUnitOutline.mutate({
                  subjectId: selectedSubjectId!,
                  subjectName: selectedSubject.name,
                  topicArea: selectedUnit.title,
                  levelBand: selectedUnit.levelBand as any,
                  additionalContext: (() => {
                    try {
                      const s = selectedUnit.standardsCovered;
                      if (typeof s === "string") return `Standards: ${s}`;
                      if (Array.isArray(s)) return `Standards: ${s.join(", ")}`;
                      return undefined;
                    } catch { return undefined; }
                  })(),
                });
              }}
            >
              {generatingUnit ? <Loader2 className="w-4 h-4 animate-spin mr-1" /> : <Wand2 className="w-4 h-4 mr-1" />}
              AI: Generate Lesson Outlines for Unit
            </Button>

            {selectedLessonId && lessonDetail && (
              <>
                <Button
                  variant="outline"
                  size="sm"
                  disabled={generatingContent}
                  onClick={() => {
                    if (!selectedSubject || !selectedUnit) return;
                    setGeneratingContent(true);
                    generateLesson.mutate({
                      unitId: selectedUnitId,
                      lessonTitle: lessonDetail.title,
                      lessonType: (lessonDetail.contentType || "instruction") as any,
                      subjectName: selectedSubject.name,
                      levelBand: selectedUnit.levelBand as string,
                    });
                  }}
                >
                  {generatingContent ? <Loader2 className="w-4 h-4 animate-spin mr-1" /> : <Wand2 className="w-4 h-4 mr-1" />}
                  AI: Regenerate Lesson Content
                </Button>

                <Button
                  variant="outline"
                  size="sm"
                  disabled={generatingAssessment}
                  onClick={() => {
                    if (!selectedSubject || !selectedUnit) return;
                    setGeneratingAssessment(true);
                    generateAssessment.mutate({
                      unitId: selectedUnitId,
                      subjectName: selectedSubject.name,
                      levelBand: selectedUnit.levelBand as string,
                      topicDescription: selectedUnit.title + (selectedUnit.description ? " - " + selectedUnit.description : ""),
                      assessmentType: "unit_quiz",
                      questionCount: 10,
                    });
                  }}
                >
                  {generatingAssessment ? <Loader2 className="w-4 h-4 animate-spin mr-1" /> : <Target className="w-4 h-4 mr-1" />}
                  AI: Generate Unit Assessment
                </Button>
              </>
            )}
          </div>
        )}

        {/* Lesson Detail & Review */}
        {selectedLessonId && lessonDetail ? (
          <div className="grid lg:grid-cols-3 gap-6">
            {/* Lesson Content Preview */}
            <div className="lg:col-span-2 border rounded-xl bg-card overflow-hidden">
              <div className="p-5 border-b flex items-center justify-between">
                <div>
                  <h2 className="text-lg font-bold text-foreground">{lessonDetail.title}</h2>
                  <p className="text-sm text-muted-foreground">{lessonDetail.summary}</p>
                </div>
                <div className="flex items-center gap-2">
                  {lessonDetail.aiGenerated && (
                    <Badge variant="outline" className="text-xs bg-blue-50 text-blue-700 border-blue-200">
                      <Wand2 className="w-3 h-3 mr-1" />
                      AI Generated
                    </Badge>
                  )}
                  {lessonDetail.humanReviewed ? (
                    <Badge variant="outline" className="text-xs bg-green-50 text-green-700 border-green-200">
                      <CheckCircle2 className="w-3 h-3 mr-1" />
                      Reviewed
                    </Badge>
                  ) : (
                    <Badge variant="outline" className="text-xs bg-amber-50 text-amber-700 border-amber-200">
                      <AlertCircle className="w-3 h-3 mr-1" />
                      Needs Review
                    </Badge>
                  )}
                </div>
              </div>

              {/* Content Blocks Preview */}
              <div className="p-5 space-y-4 max-h-[600px] overflow-y-auto">
                {(() => {
                  const blocks = (() => {
                    try {
                      if (typeof lessonDetail.contentBlocks === "string") return JSON.parse(lessonDetail.contentBlocks);
                      return lessonDetail.contentBlocks || [];
                    } catch { return []; }
                  })();

                  if (blocks.length === 0) {
                    return (
                      <div className="text-center py-8">
                        <Wand2 className="w-8 h-8 text-muted-foreground mx-auto mb-3" />
                        <p className="text-muted-foreground">No content yet. Click "AI: Regenerate Lesson Content" to generate.</p>
                      </div>
                    );
                  }

                  return blocks.map((block: any, idx: number) => (
                    <div key={idx} className="text-sm">
                      <Badge variant="outline" className="text-xs mb-1">{block.type}</Badge>
                      {block.type === "key_concept" && (
                        <div className="bg-blue-50 dark:bg-blue-950/20 rounded-lg p-3 border-l-4 border-blue-500">
                          <h4 className="font-bold text-blue-900 dark:text-blue-300 text-sm">{block.data?.title}</h4>
                          <p className="text-xs text-blue-800 dark:text-blue-200 mt-1">{block.data?.content}</p>
                        </div>
                      )}
                      {block.type === "text" && (
                        <p className="text-muted-foreground text-sm">{block.data?.content}</p>
                      )}
                      {block.type === "practice_problem" && (
                        <div className="space-y-2">
                          {(block.data?.problems || []).map((p: any, pi: number) => (
                            <div key={pi} className="bg-card border rounded p-2 text-xs">
                              <p className="font-medium">Q: {p.question}</p>
                              <p className="text-green-600 mt-1">A: {p.answer}</p>
                            </div>
                          ))}
                        </div>
                      )}
                      {block.type === "real_world_connection" && (
                        <div className="bg-green-50 dark:bg-green-950/20 rounded-lg p-3 border-l-4 border-green-500">
                          <h4 className="font-bold text-green-900 dark:text-green-300 text-sm">{block.data?.title}</h4>
                          <p className="text-xs text-green-800 dark:text-green-200 mt-1">{block.data?.content}</p>
                        </div>
                      )}
                      {block.type === "discussion_prompt" && (
                        <div className="bg-purple-50 dark:bg-purple-950/20 rounded-lg p-3 border-l-4 border-purple-500">
                          <p className="text-xs text-purple-800 dark:text-purple-200">{block.data?.prompt}</p>
                        </div>
                      )}
                    </div>
                  ));
                })()}
              </div>

              {/* Review Action */}
              {!lessonDetail.humanReviewed && (
                <div className="p-4 border-t bg-amber-50/50">
                  <Button
                    className="w-full bg-emerald-600 hover:bg-emerald-700"
                    onClick={() => {
                      reviewContent.mutate({
                        targetType: "lesson",
                        targetId: selectedLessonId,
                        approved: true,
                      });
                    }}
                  >
                    <CheckCircle2 className="w-4 h-4 mr-2" />
                    Approve & Mark as Reviewed
                  </Button>
                </div>
              )}
            </div>

            {/* Human Notes Panel */}
            <div className="lg:col-span-1 space-y-4">
              <div className="border rounded-xl bg-card p-4">
                <h3 className="font-bold text-foreground mb-3 flex items-center gap-2">
                  <MessageSquare className="w-4 h-4 text-emerald-600" />
                  Educator Notes
                </h3>
                <p className="text-xs text-muted-foreground mb-4">
                  Add your perspective, cultural context, real-world stories, or teaching tips. 
                  Published notes appear alongside the AI content for students.
                </p>

                {/* Existing Notes */}
                {humanNotes && humanNotes.length > 0 ? (
                  <div className="space-y-3 mb-4">
                    {humanNotes.map((note: any) => (
                      <div key={note.id} className="border rounded-lg p-3 bg-background">
                        <div className="flex items-center justify-between mb-2">
                          <Badge variant="outline" className="text-xs capitalize">
                            {(note.noteType || "general").replace(/_/g, " ")}
                          </Badge>
                          {note.isPublished ? (
                            <Badge variant="outline" className="text-xs bg-green-50 text-green-700 border-green-200">
                              <Eye className="w-3 h-3 mr-1" />
                              Published
                            </Badge>
                          ) : (
                            <Button
                              variant="ghost"
                              size="sm"
                              className="text-xs h-6"
                              onClick={() => publishNote.mutate({ noteId: note.id })}
                            >
                              Publish
                            </Button>
                          )}
                        </div>
                        <p className="text-sm text-foreground">{note.content}</p>
                        {note.authorName && (
                          <p className="text-xs text-muted-foreground mt-1">— {note.authorName}</p>
                        )}
                      </div>
                    ))}
                  </div>
                ) : (
                  <p className="text-sm text-muted-foreground italic mb-4">No educator notes yet. Be the first to add your perspective.</p>
                )}

                {/* Add Note Form */}
                {addingNote ? (
                  <div className="space-y-3">
                    <Select value={humanNoteType} onValueChange={setHumanNoteType}>
                      <SelectTrigger className="h-8 text-xs">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="cultural_context">Cultural Context</SelectItem>
                        <SelectItem value="teaching_tip">Teaching Tip</SelectItem>
                        <SelectItem value="real_world_story">Real-World Story</SelectItem>
                        <SelectItem value="correction">Correction</SelectItem>
                        <SelectItem value="enrichment">Enrichment</SelectItem>
                        <SelectItem value="discussion_guide">Discussion Guide</SelectItem>
                      </SelectContent>
                    </Select>
                    <Textarea
                      placeholder="Share your perspective, a real-world story, cultural context, or teaching insight..."
                      value={humanNoteContent}
                      onChange={(e) => setHumanNoteContent(e.target.value)}
                      rows={4}
                      className="text-sm"
                    />
                    <div className="flex gap-2">
                      <Button
                        size="sm"
                        className="flex-1 bg-emerald-600 hover:bg-emerald-700"
                        disabled={!humanNoteContent.trim()}
                        onClick={() => {
                          addHumanNote.mutate({
                            targetType: "lesson",
                            targetId: selectedLessonId,
                            noteType: humanNoteType as any,
                            content: humanNoteContent,
                          });
                        }}
                      >
                        <Plus className="w-3 h-3 mr-1" />
                        Add Note
                      </Button>
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => { setAddingNote(false); setHumanNoteContent(""); }}
                      >
                        Cancel
                      </Button>
                    </div>
                  </div>
                ) : (
                  <Button
                    variant="outline"
                    size="sm"
                    className="w-full"
                    onClick={() => setAddingNote(true)}
                  >
                    <Plus className="w-3 h-3 mr-1" />
                    Add Educator Note
                  </Button>
                )}
              </div>

              {/* Vocabulary Preview */}
              {lessonDetail.vocabularyTerms && (
                <div className="border rounded-xl bg-card p-4">
                  <h3 className="font-bold text-foreground mb-2 text-sm">Vocabulary Terms</h3>
                  <div className="space-y-2">
                    {(() => {
                      const vocab = (() => {
                        try {
                          if (typeof lessonDetail.vocabularyTerms === "string") return JSON.parse(lessonDetail.vocabularyTerms);
                          return lessonDetail.vocabularyTerms || [];
                        } catch { return []; }
                      })();
                      return vocab.map((v: any, vi: number) => (
                        <div key={vi} className="text-xs">
                          <span className="font-semibold text-foreground">{v.term}:</span>
                          <span className="text-muted-foreground ml-1">{v.definition}</span>
                        </div>
                      ));
                    })()}
                  </div>
                </div>
              )}
            </div>
          </div>
        ) : selectedUnitId ? (
          <div className="text-center py-12 border rounded-xl bg-card">
            <BookOpen className="w-10 h-10 text-muted-foreground mx-auto mb-3" />
            <h3 className="font-semibold text-foreground mb-1">Select a Lesson to Review</h3>
            <p className="text-sm text-muted-foreground mb-4">
              Choose a lesson from the dropdown above, or generate new lesson outlines for this unit.
            </p>
            {(!lessons || lessons.length === 0) && (
              <Button
                variant="outline"
                disabled={generatingUnit}
                onClick={() => {
                  if (!selectedUnit || !selectedSubject) return;
                  setGeneratingUnit(true);
                  generateUnitOutline.mutate({
                    unitId: selectedUnitId,
                    subjectName: selectedSubject.name,
                    unitTitle: selectedUnit.title,
                    levelBand: selectedUnit.levelBand as string,
                    standardsCovered: (() => {
                      try {
                        const s = selectedUnit.standardsCovered;
                        if (typeof s === "string") return JSON.parse(s);
                        return s || [];
                      } catch { return []; }
                    })(),
                  });
                }}
              >
                {generatingUnit ? <Loader2 className="w-4 h-4 animate-spin mr-1" /> : <Wand2 className="w-4 h-4 mr-1" />}
                AI: Generate Lesson Outlines
              </Button>
            )}
          </div>
        ) : (
          <div className="text-center py-12 border rounded-xl bg-card">
            <Sparkles className="w-10 h-10 text-amber-400 mx-auto mb-3" />
            <h3 className="font-semibold text-foreground mb-1">Select a Subject and Unit</h3>
            <p className="text-sm text-muted-foreground">
              Use the dropdowns above to navigate to the content you want to review or generate.
            </p>
          </div>
        )}
      </div>
    </DashboardLayout>
  );
}
