CREATE TABLE IF NOT EXISTS `position_requisitions` (
  `id` int AUTO_INCREMENT NOT NULL,
  `positionId` varchar(100) NOT NULL,
  `positionTitle` varchar(255) NOT NULL,
  `department` varchar(100) NOT NULL,
  `entity` varchar(255) NOT NULL,
  `tier` varchar(50) NOT NULL,
  `requestedBy` int NOT NULL,
  `requestedByName` varchar(255),
  `justification` text NOT NULL,
  `budgetApproved` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  `salaryRange` varchar(100),
  `targetStartDate` timestamp,
  `urgency` enum('low','medium','high','critical') NOT NULL DEFAULT 'medium',
  `status` enum('draft','submitted','under_review','approved','rejected','filled','cancelled') NOT NULL DEFAULT 'draft',
  `approvedBy` int,
  `approvedByName` varchar(255),
  `approvalDate` timestamp,
  `approvalNotes` text,
  `candidateName` varchar(255),
  `candidateEmail` varchar(320),
  `filledDate` timestamp,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `position_requisitions_id` PRIMARY KEY(`id`)
);
