-- Contractor Transitions table
CREATE TABLE IF NOT EXISTS `contractor_transitions` (
  `id` int AUTO_INCREMENT NOT NULL,
  `employeeId` int NOT NULL,
  `employeeName` varchar(255) NOT NULL,
  `initiatedBy` int NOT NULL,
  `initiatedByName` varchar(255),
  `phase` enum('initiated','training_assigned','training_in_progress','training_completed','entity_formation','entity_verified','contract_pending','contract_signed','completed','cancelled') NOT NULL DEFAULT 'initiated',
  `trainingModuleId` int,
  `trainingStartDate` timestamp,
  `trainingCompletionDate` timestamp,
  `trainingScore` int,
  `certificationIssued` boolean NOT NULL DEFAULT false,
  `businessEntityId` int,
  `entityName` varchar(255),
  `entityType` varchar(100),
  `entityFormationDate` timestamp,
  `einObtained` boolean NOT NULL DEFAULT false,
  `businessBankSetup` boolean NOT NULL DEFAULT false,
  `contractId` int,
  `contractSignedDate` timestamp,
  `contractTerms` json,
  `status` enum('active','completed','cancelled','on_hold') NOT NULL DEFAULT 'active',
  `completedDate` timestamp,
  `cancellationReason` text,
  `notes` text,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `contractor_transitions_id` PRIMARY KEY(`id`)
);

-- Impact Metrics table
CREATE TABLE IF NOT EXISTS `impact_metrics` (
  `id` int AUTO_INCREMENT NOT NULL,
  `metricType` enum('employees_trained','employees_transitioned','businesses_formed','contractor_retention','contractor_revenue','jobs_created','community_members_served','scholarships_awarded','volunteer_hours') NOT NULL,
  `periodType` enum('monthly','quarterly','annual') NOT NULL,
  `periodStart` timestamp NOT NULL,
  `periodEnd` timestamp NOT NULL,
  `targetValue` decimal(15,2),
  `actualValue` decimal(15,2) NOT NULL,
  `previousPeriodValue` decimal(15,2),
  `entityId` int,
  `entityName` varchar(255),
  `programName` varchar(255),
  `grantId` varchar(100),
  `notes` text,
  `dataSource` varchar(255),
  `verifiedBy` int,
  `verifiedAt` timestamp,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `impact_metrics_id` PRIMARY KEY(`id`)
);

-- Contractor Businesses table
CREATE TABLE IF NOT EXISTS `contractor_businesses` (
  `id` int AUTO_INCREMENT NOT NULL,
  `transitionId` int NOT NULL,
  `contractorId` int NOT NULL,
  `contractorName` varchar(255) NOT NULL,
  `businessName` varchar(255) NOT NULL,
  `businessType` varchar(100),
  `ein` varchar(20),
  `stateOfFormation` varchar(50),
  `formationDate` timestamp,
  `status` enum('active','inactive','dissolved') NOT NULL DEFAULT 'active',
  `annualRevenue` decimal(15,2),
  `revenueYear` int,
  `employeesHired` int DEFAULT 0,
  `platformSubscription` enum('none','basic','professional','enterprise') NOT NULL DEFAULT 'none',
  `platformActiveDate` timestamp,
  `activeContractWithLaws` boolean NOT NULL DEFAULT false,
  `lastContractDate` timestamp,
  `totalContractValue` decimal(15,2),
  `notes` text,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `contractor_businesses_id` PRIMARY KEY(`id`)
);
