-- Pending House Heirs - Heir Queue for grandchildren and future generations
CREATE TABLE IF NOT EXISTS `pending_house_heirs` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `parentHouseId` int NOT NULL,
  `parentHouseName` varchar(255),
  `parentMemberId` int,
  `parentMemberName` varchar(255),
  `otherParentName` varchar(255),
  `fullName` varchar(255) NOT NULL,
  `dateOfBirth` timestamp NOT NULL,
  `relationship` enum('grandchild', 'great_grandchild', 'step_grandchild', 'adopted_grandchild', 'foster_grandchild', 'other') NOT NULL,
  `generation` int NOT NULL DEFAULT 3,
  `email` varchar(255),
  `phone` varchar(50),
  `projectedHouseName` varchar(255),
  `projectedHouseType` enum('bloodline', 'mirrored', 'adaptive') DEFAULT 'bloodline',
  `activationTrigger` enum('age_18', 'age_21', 'age_25', 'education', 'marriage', 'first_business', 'manual', 'custom') NOT NULL DEFAULT 'age_18',
  `customActivationCriteria` text,
  `projectedActivationDate` timestamp,
  `accumulatedAmount` decimal(18,2) DEFAULT '0',
  `lastAccumulationDate` timestamp,
  `accumulationAccountId` int,
  `distributionPercentage` decimal(5,2) NOT NULL,
  `percentageLocked` boolean DEFAULT false,
  `status` enum('pending', 'eligible', 'activating', 'activated', 'deferred', 'removed') NOT NULL DEFAULT 'pending',
  `activatedHouseId` int,
  `activatedAt` timestamp,
  `activatedBy` int,
  `registeredBy` int NOT NULL,
  `registeredAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `notes` text
);

-- Pending Heir Placeholders - For children not yet born
CREATE TABLE IF NOT EXISTS `pending_heir_placeholders` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `parentHouseId` int NOT NULL,
  `parentMemberId` int NOT NULL,
  `parentMemberName` varchar(255),
  `placeholderName` varchar(255) NOT NULL,
  `projectedHouseType` enum('bloodline', 'mirrored', 'adaptive') DEFAULT 'bloodline',
  `reservedPercentage` decimal(5,2) NOT NULL,
  `reservedAmount` decimal(18,2) DEFAULT '0',
  `status` enum('active', 'converted', 'released') NOT NULL DEFAULT 'active',
  `convertedToHeirId` int,
  `convertedAt` timestamp,
  `expiresAt` timestamp,
  `createdBy` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
