/**
 * L.A.W.S. Quest - Commercial Game Product
 * Owned by The The The L.A.W.S. Collective, LLC
 * 
 * Expanded quest content for all four realms
 * Each realm has 20+ quests organized into storylines
 */

import type { Quest, MiniGameType } from "./types";

// ============================================
// STORYLINE DEFINITIONS
// ============================================

export interface Storyline {
  id: string;
  name: string;
  description: string;
  realm: "land" | "air" | "water" | "self";
  questIds: string[];
  unlockRequirements?: {
    level?: number;
    completedStorylines?: string[];
  };
}

export const STORYLINES: Storyline[] = [
  // LAND Storylines
  {
    id: "land-origins",
    name: "Roots of the Ancestors",
    description: "Discover your family's history and reconnect with your ancestral heritage.",
    realm: "land",
    questIds: ["land-origins-1", "land-origins-2", "land-origins-3", "land-origins-4", "land-origins-5"],
  },
  {
    id: "land-property",
    name: "Sacred Ground",
    description: "Learn the foundations of land ownership and territorial sovereignty.",
    realm: "land",
    questIds: ["land-property-1", "land-property-2", "land-property-3", "land-property-4"],
    unlockRequirements: { completedStorylines: ["land-origins"] },
  },
  {
    id: "land-stewardship",
    name: "Keeper of Resources",
    description: "Master sustainable resource management for future generations.",
    realm: "land",
    questIds: ["land-steward-1", "land-steward-2", "land-steward-3", "land-steward-4"],
    unlockRequirements: { level: 15, completedStorylines: ["land-property"] },
  },
  {
    id: "land-legacy",
    name: "The Eternal Foundation",
    description: "Build a lasting legacy rooted in the land.",
    realm: "land",
    questIds: ["land-legacy-1", "land-legacy-2", "land-legacy-3"],
    unlockRequirements: { level: 30, completedStorylines: ["land-stewardship"] },
  },

  // AIR Storylines
  {
    id: "air-communication",
    name: "Voice of Clarity",
    description: "Master the art of clear and effective communication.",
    realm: "air",
    questIds: ["air-comm-1", "air-comm-2", "air-comm-3", "air-comm-4", "air-comm-5"],
  },
  {
    id: "air-knowledge",
    name: "The Scholar's Path",
    description: "Pursue knowledge and expand your understanding of the world.",
    realm: "air",
    questIds: ["air-know-1", "air-know-2", "air-know-3", "air-know-4"],
    unlockRequirements: { completedStorylines: ["air-communication"] },
  },
  {
    id: "air-wisdom",
    name: "Keeper of Wisdom",
    description: "Transform knowledge into wisdom and share it with others.",
    realm: "air",
    questIds: ["air-wisdom-1", "air-wisdom-2", "air-wisdom-3", "air-wisdom-4"],
    unlockRequirements: { level: 15, completedStorylines: ["air-knowledge"] },
  },
  {
    id: "air-mentor",
    name: "The Great Teacher",
    description: "Become a mentor and guide others on their journey.",
    realm: "air",
    questIds: ["air-mentor-1", "air-mentor-2", "air-mentor-3"],
    unlockRequirements: { level: 30, completedStorylines: ["air-wisdom"] },
  },

  // WATER Storylines
  {
    id: "water-awareness",
    name: "Still Waters",
    description: "Begin your journey of emotional self-awareness.",
    realm: "water",
    questIds: ["water-aware-1", "water-aware-2", "water-aware-3", "water-aware-4", "water-aware-5"],
  },
  {
    id: "water-healing",
    name: "Currents of Healing",
    description: "Learn to process emotions and heal from past wounds.",
    realm: "water",
    questIds: ["water-heal-1", "water-heal-2", "water-heal-3", "water-heal-4"],
    unlockRequirements: { completedStorylines: ["water-awareness"] },
  },
  {
    id: "water-balance",
    name: "The Flowing Path",
    description: "Achieve balance between emotion and reason.",
    realm: "water",
    questIds: ["water-balance-1", "water-balance-2", "water-balance-3", "water-balance-4"],
    unlockRequirements: { level: 15, completedStorylines: ["water-healing"] },
  },
  {
    id: "water-mastery",
    name: "Ocean's Depth",
    description: "Attain mastery over your emotional landscape.",
    realm: "water",
    questIds: ["water-master-1", "water-master-2", "water-master-3"],
    unlockRequirements: { level: 30, completedStorylines: ["water-balance"] },
  },

  // SELF Storylines
  {
    id: "self-purpose",
    name: "The Inner Flame",
    description: "Discover your core values and life's purpose.",
    realm: "self",
    questIds: ["self-purpose-1", "self-purpose-2", "self-purpose-3", "self-purpose-4", "self-purpose-5"],
  },
  {
    id: "self-foundation",
    name: "Building Blocks",
    description: "Establish the financial foundations for your future.",
    realm: "self",
    questIds: ["self-found-1", "self-found-2", "self-found-3", "self-found-4"],
    unlockRequirements: { completedStorylines: ["self-purpose"] },
  },
  {
    id: "self-growth",
    name: "The Entrepreneur's Way",
    description: "Develop business skills and entrepreneurial mindset.",
    realm: "self",
    questIds: ["self-grow-1", "self-grow-2", "self-grow-3", "self-grow-4"],
    unlockRequirements: { level: 15, completedStorylines: ["self-foundation"] },
  },
  {
    id: "self-sovereignty",
    name: "The Sovereign Path",
    description: "Achieve true financial sovereignty and build generational wealth.",
    realm: "self",
    questIds: ["self-sov-1", "self-sov-2", "self-sov-3"],
    unlockRequirements: { level: 30, completedStorylines: ["self-growth"] },
  },
];

// ============================================
// EXPANDED QUESTS - LAND REALM
// ============================================

export const LAND_QUESTS: Quest[] = [
  // Roots of the Ancestors Storyline
  {
    id: "land-origins-1",
    name: "Roots of Origin",
    description: "Begin documenting your family tree.",
    longDescription: "Every great journey begins with understanding where you came from. In this quest, you'll start the process of documenting your family history, beginning with what you know and building from there. Your ancestors' stories are waiting to be discovered.",
    realm: "land",
    difficulty: "beginner",
    chapter: 1,
    requirements: {},
    rewards: { experience: 50, tokens: 10, statBoosts: { land: 2 } },
    status: "available",
    miniGame: "reflection",
    miniGameConfig: { type: "reflection", difficulty: 1, questionCount: 3, passingScore: 60 },
    energyCost: 10,
    estimatedTime: 5,
    repeatability: "once",
    completionCount: 0,
    storyline: "land-origins",
    npcGiver: "elder-root",
  },
  {
    id: "land-origins-2",
    name: "Names and Faces",
    description: "Learn about your grandparents and their stories.",
    longDescription: "The stories of your grandparents hold keys to understanding your family's journey. Through interviews, photos, and memories, piece together the lives of those who came before your parents.",
    realm: "land",
    difficulty: "beginner",
    chapter: 1,
    requirements: { stats: { land: 2 } },
    rewards: { experience: 75, tokens: 15, statBoosts: { land: 2 }, items: [{ itemId: "scroll-ancestry", quantity: 1 }] },
    status: "locked",
    miniGame: "memory",
    miniGameConfig: { type: "memory", difficulty: 2, timeLimit: 120, passingScore: 70 },
    energyCost: 12,
    estimatedTime: 8,
    repeatability: "once",
    completionCount: 0,
    storyline: "land-origins",
    prerequisites: ["land-origins-1"],
  },
  {
    id: "land-origins-3",
    name: "The Great Migration",
    description: "Trace your family's geographic journey.",
    longDescription: "Families move for many reasons—opportunity, survival, hope. Map the geographic journey of your ancestors and understand the forces that shaped their decisions to move.",
    realm: "land",
    difficulty: "intermediate",
    chapter: 1,
    requirements: { stats: { land: 4 } },
    rewards: { experience: 100, tokens: 20, statBoosts: { land: 3 } },
    status: "locked",
    miniGame: "trivia",
    miniGameConfig: { type: "trivia", difficulty: 3, questionCount: 5, passingScore: 60 },
    energyCost: 15,
    estimatedTime: 10,
    repeatability: "once",
    completionCount: 0,
    storyline: "land-origins",
    prerequisites: ["land-origins-2"],
  },
  {
    id: "land-origins-4",
    name: "Traditions and Customs",
    description: "Document your family's cultural traditions.",
    longDescription: "Every family carries traditions—some spoken, some unspoken. These customs connect us to our heritage. Document the traditions your family practices and understand their origins.",
    realm: "land",
    difficulty: "intermediate",
    chapter: 1,
    requirements: { stats: { land: 6 } },
    rewards: { experience: 125, tokens: 25, statBoosts: { land: 3, air: 1 } },
    status: "locked",
    miniGame: "reflection",
    miniGameConfig: { type: "reflection", difficulty: 3, questionCount: 4, passingScore: 70 },
    energyCost: 15,
    estimatedTime: 12,
    repeatability: "once",
    completionCount: 0,
    storyline: "land-origins",
    prerequisites: ["land-origins-3"],
  },
  {
    id: "land-origins-5",
    name: "The Ancestral Archive",
    description: "Create a comprehensive family history document.",
    longDescription: "Compile everything you've learned into a lasting document that future generations can reference. This archive becomes a gift to those who come after you.",
    realm: "land",
    difficulty: "advanced",
    chapter: 1,
    requirements: { stats: { land: 8 } },
    rewards: { 
      experience: 200, 
      tokens: 40, 
      statBoosts: { land: 5 },
      items: [{ itemId: "artifact-family-tree", quantity: 1 }],
      achievements: ["ancestry-complete"]
    },
    status: "locked",
    miniGame: "strategy",
    miniGameConfig: { type: "strategy", difficulty: 4, timeLimit: 180, passingScore: 75 },
    energyCost: 20,
    estimatedTime: 15,
    repeatability: "once",
    completionCount: 0,
    storyline: "land-origins",
    prerequisites: ["land-origins-4"],
  },

  // Sacred Ground Storyline
  {
    id: "land-property-1",
    name: "Understanding Deeds",
    description: "Learn the basics of property documentation.",
    longDescription: "A deed is more than paper—it's proof of ownership, a legal foundation for your stake in the land. Learn to read and understand property documents.",
    realm: "land",
    difficulty: "intermediate",
    chapter: 2,
    requirements: { stats: { land: 10 } },
    rewards: { experience: 100, tokens: 25, statBoosts: { land: 3 } },
    status: "locked",
    miniGame: "trivia",
    miniGameConfig: { type: "trivia", difficulty: 4, questionCount: 6, passingScore: 65 },
    energyCost: 15,
    estimatedTime: 10,
    repeatability: "once",
    completionCount: 0,
    storyline: "land-property",
    prerequisites: ["land-origins-5"],
    npcGiver: "elder-root",
  },
  {
    id: "land-property-2",
    name: "Rights and Responsibilities",
    description: "Understand property rights and owner responsibilities.",
    longDescription: "Ownership comes with both rights and responsibilities. Learn what it means to truly own land and the obligations that come with it.",
    realm: "land",
    difficulty: "intermediate",
    chapter: 2,
    requirements: { stats: { land: 12 } },
    rewards: { experience: 125, tokens: 30, statBoosts: { land: 3, self: 1 } },
    status: "locked",
    miniGame: "trivia",
    miniGameConfig: { type: "trivia", difficulty: 4, questionCount: 6, passingScore: 65 },
    energyCost: 15,
    estimatedTime: 12,
    repeatability: "once",
    completionCount: 0,
    storyline: "land-property",
    prerequisites: ["land-property-1"],
  },
  {
    id: "land-property-3",
    name: "Territorial Sovereignty",
    description: "Explore the concept of sovereign land ownership.",
    longDescription: "True sovereignty begins with understanding your rights over your own territory. Learn about allodial titles, land patents, and the history of land ownership.",
    realm: "land",
    difficulty: "advanced",
    chapter: 2,
    requirements: { stats: { land: 14 } },
    rewards: { experience: 175, tokens: 40, statBoosts: { land: 4, self: 2 } },
    status: "locked",
    miniGame: "trivia",
    miniGameConfig: { type: "trivia", difficulty: 5, questionCount: 7, passingScore: 70 },
    energyCost: 18,
    estimatedTime: 15,
    repeatability: "once",
    completionCount: 0,
    storyline: "land-property",
    prerequisites: ["land-property-2"],
  },
  {
    id: "land-property-4",
    name: "The First Acquisition",
    description: "Simulate your first property acquisition.",
    longDescription: "Put your knowledge to the test by simulating the process of acquiring property. From research to closing, experience every step.",
    realm: "land",
    difficulty: "advanced",
    chapter: 2,
    requirements: { stats: { land: 16 } },
    rewards: { 
      experience: 250, 
      tokens: 60, 
      statBoosts: { land: 5, self: 3 },
      achievements: ["property-scholar"]
    },
    status: "locked",
    miniGame: "strategy",
    miniGameConfig: { type: "strategy", difficulty: 6, timeLimit: 240, passingScore: 70 },
    energyCost: 22,
    estimatedTime: 20,
    repeatability: "once",
    completionCount: 0,
    storyline: "land-property",
    prerequisites: ["land-property-3"],
  },

  // Keeper of Resources Storyline
  {
    id: "land-steward-1",
    name: "Resource Assessment",
    description: "Learn to evaluate and inventory resources.",
    longDescription: "Before you can manage resources, you must understand what you have. Learn systematic approaches to assessing and inventorying resources.",
    realm: "land",
    difficulty: "advanced",
    chapter: 3,
    requirements: { level: 15, stats: { land: 18 } },
    rewards: { experience: 150, tokens: 35, statBoosts: { land: 4 } },
    status: "locked",
    miniGame: "puzzle",
    miniGameConfig: { type: "puzzle", difficulty: 5, timeLimit: 180, passingScore: 70 },
    energyCost: 18,
    estimatedTime: 12,
    repeatability: "once",
    completionCount: 0,
    storyline: "land-stewardship",
    prerequisites: ["land-property-4"],
  },
  {
    id: "land-steward-2",
    name: "Sustainable Practices",
    description: "Master sustainable resource management.",
    longDescription: "True wealth is renewable. Learn practices that allow resources to regenerate and grow rather than deplete.",
    realm: "land",
    difficulty: "advanced",
    chapter: 3,
    requirements: { stats: { land: 20 } },
    rewards: { experience: 175, tokens: 40, statBoosts: { land: 4, water: 2 } },
    status: "locked",
    miniGame: "strategy",
    miniGameConfig: { type: "strategy", difficulty: 5, timeLimit: 200, passingScore: 70 },
    energyCost: 20,
    estimatedTime: 15,
    repeatability: "once",
    completionCount: 0,
    storyline: "land-stewardship",
    prerequisites: ["land-steward-1"],
  },
  {
    id: "land-steward-3",
    name: "Generational Planning",
    description: "Plan resource management across generations.",
    longDescription: "The greatest stewards think beyond their own lifetime. Learn to create plans that will benefit your children's children.",
    realm: "land",
    difficulty: "master",
    chapter: 3,
    requirements: { stats: { land: 22 } },
    rewards: { experience: 225, tokens: 50, statBoosts: { land: 5, self: 2 } },
    status: "locked",
    miniGame: "strategy",
    miniGameConfig: { type: "strategy", difficulty: 6, timeLimit: 240, passingScore: 75 },
    energyCost: 22,
    estimatedTime: 18,
    repeatability: "once",
    completionCount: 0,
    storyline: "land-stewardship",
    prerequisites: ["land-steward-2"],
  },
  {
    id: "land-steward-4",
    name: "The Steward's Oath",
    description: "Commit to the principles of responsible stewardship.",
    longDescription: "Take the Steward's Oath—a commitment to manage resources responsibly for the benefit of all who come after you.",
    realm: "land",
    difficulty: "master",
    chapter: 3,
    requirements: { stats: { land: 25 } },
    rewards: { 
      experience: 300, 
      tokens: 75, 
      statBoosts: { land: 6, water: 2, self: 2 },
      achievements: ["master-steward"]
    },
    status: "locked",
    miniGame: "reflection",
    miniGameConfig: { type: "reflection", difficulty: 5, questionCount: 5, passingScore: 80 },
    energyCost: 25,
    estimatedTime: 20,
    repeatability: "once",
    completionCount: 0,
    storyline: "land-stewardship",
    prerequisites: ["land-steward-3"],
  },
];

// ============================================
// EXPANDED QUESTS - AIR REALM
// ============================================

export const AIR_QUESTS: Quest[] = [
  // Voice of Clarity Storyline
  {
    id: "air-comm-1",
    name: "First Words",
    description: "Learn the fundamentals of clear communication.",
    longDescription: "Words have power. In this quest, you'll learn the basics of expressing yourself clearly and effectively—skills that will serve you in every realm.",
    realm: "air",
    difficulty: "beginner",
    chapter: 1,
    requirements: {},
    rewards: { experience: 50, tokens: 10, statBoosts: { air: 2 } },
    status: "available",
    miniGame: "trivia",
    miniGameConfig: { type: "trivia", difficulty: 1, questionCount: 5, passingScore: 60 },
    energyCost: 10,
    estimatedTime: 5,
    repeatability: "once",
    completionCount: 0,
    storyline: "air-communication",
    npcGiver: "sage-breeze",
  },
  {
    id: "air-comm-2",
    name: "Active Listening",
    description: "Master the art of truly hearing others.",
    longDescription: "Communication is not just about speaking—it's about listening. Learn techniques for active listening that will transform your relationships.",
    realm: "air",
    difficulty: "beginner",
    chapter: 1,
    requirements: { stats: { air: 2 } },
    rewards: { experience: 75, tokens: 15, statBoosts: { air: 2, water: 1 } },
    status: "locked",
    miniGame: "memory",
    miniGameConfig: { type: "memory", difficulty: 2, timeLimit: 90, passingScore: 70 },
    energyCost: 12,
    estimatedTime: 8,
    repeatability: "once",
    completionCount: 0,
    storyline: "air-communication",
    prerequisites: ["air-comm-1"],
  },
  {
    id: "air-comm-3",
    name: "Written Expression",
    description: "Develop your written communication skills.",
    longDescription: "The written word endures. Learn to express complex ideas clearly in writing—a skill essential for documentation, contracts, and legacy building.",
    realm: "air",
    difficulty: "intermediate",
    chapter: 1,
    requirements: { stats: { air: 4 } },
    rewards: { experience: 100, tokens: 20, statBoosts: { air: 3 } },
    status: "locked",
    miniGame: "word",
    miniGameConfig: { type: "word", difficulty: 3, timeLimit: 120, passingScore: 65 },
    energyCost: 15,
    estimatedTime: 10,
    repeatability: "once",
    completionCount: 0,
    storyline: "air-communication",
    prerequisites: ["air-comm-2"],
  },
  {
    id: "air-comm-4",
    name: "Persuasion and Influence",
    description: "Learn ethical persuasion techniques.",
    longDescription: "The ability to persuade is a powerful tool. Learn ethical techniques for influencing others while maintaining integrity.",
    realm: "air",
    difficulty: "intermediate",
    chapter: 1,
    requirements: { stats: { air: 6 } },
    rewards: { experience: 125, tokens: 25, statBoosts: { air: 3, self: 1 } },
    status: "locked",
    miniGame: "trivia",
    miniGameConfig: { type: "trivia", difficulty: 4, questionCount: 6, passingScore: 65 },
    energyCost: 15,
    estimatedTime: 12,
    repeatability: "once",
    completionCount: 0,
    storyline: "air-communication",
    prerequisites: ["air-comm-3"],
  },
  {
    id: "air-comm-5",
    name: "The Art of Negotiation",
    description: "Master negotiation for win-win outcomes.",
    longDescription: "True negotiation creates value for all parties. Learn frameworks for negotiating agreements that benefit everyone involved.",
    realm: "air",
    difficulty: "advanced",
    chapter: 1,
    requirements: { stats: { air: 8 } },
    rewards: { 
      experience: 200, 
      tokens: 40, 
      statBoosts: { air: 5, self: 2 },
      achievements: ["master-communicator"]
    },
    status: "locked",
    miniGame: "strategy",
    miniGameConfig: { type: "strategy", difficulty: 5, timeLimit: 180, passingScore: 70 },
    energyCost: 20,
    estimatedTime: 15,
    repeatability: "once",
    completionCount: 0,
    storyline: "air-communication",
    prerequisites: ["air-comm-4"],
  },

  // The Scholar's Path Storyline
  {
    id: "air-know-1",
    name: "The Learning Mind",
    description: "Develop effective learning strategies.",
    longDescription: "Learning how to learn is the most valuable skill. Discover techniques for absorbing, retaining, and applying new knowledge.",
    realm: "air",
    difficulty: "intermediate",
    chapter: 2,
    requirements: { stats: { air: 10 } },
    rewards: { experience: 100, tokens: 25, statBoosts: { air: 3 } },
    status: "locked",
    miniGame: "memory",
    miniGameConfig: { type: "memory", difficulty: 4, timeLimit: 120, passingScore: 75 },
    energyCost: 15,
    estimatedTime: 10,
    repeatability: "once",
    completionCount: 0,
    storyline: "air-knowledge",
    prerequisites: ["air-comm-5"],
    npcGiver: "sage-breeze",
  },
  {
    id: "air-know-2",
    name: "Critical Thinking",
    description: "Sharpen your analytical abilities.",
    longDescription: "Not all information is equal. Learn to evaluate sources, identify biases, and think critically about the information you encounter.",
    realm: "air",
    difficulty: "intermediate",
    chapter: 2,
    requirements: { stats: { air: 12 } },
    rewards: { experience: 125, tokens: 30, statBoosts: { air: 3, water: 1 } },
    status: "locked",
    miniGame: "puzzle",
    miniGameConfig: { type: "puzzle", difficulty: 4, timeLimit: 150, passingScore: 70 },
    energyCost: 15,
    estimatedTime: 12,
    repeatability: "once",
    completionCount: 0,
    storyline: "air-knowledge",
    prerequisites: ["air-know-1"],
  },
  {
    id: "air-know-3",
    name: "Research Methods",
    description: "Learn systematic approaches to finding truth.",
    longDescription: "Truth requires diligent seeking. Master research methodologies that help you find accurate, reliable information.",
    realm: "air",
    difficulty: "advanced",
    chapter: 2,
    requirements: { stats: { air: 14 } },
    rewards: { experience: 175, tokens: 40, statBoosts: { air: 4 } },
    status: "locked",
    miniGame: "trivia",
    miniGameConfig: { type: "trivia", difficulty: 5, questionCount: 7, passingScore: 70 },
    energyCost: 18,
    estimatedTime: 15,
    repeatability: "once",
    completionCount: 0,
    storyline: "air-knowledge",
    prerequisites: ["air-know-2"],
  },
  {
    id: "air-know-4",
    name: "The Scholar's Library",
    description: "Build your personal knowledge repository.",
    longDescription: "A scholar's greatest asset is their library—not just of books, but of organized knowledge. Create a system for storing and retrieving what you learn.",
    realm: "air",
    difficulty: "advanced",
    chapter: 2,
    requirements: { stats: { air: 16 } },
    rewards: { 
      experience: 250, 
      tokens: 60, 
      statBoosts: { air: 5, land: 2 },
      items: [{ itemId: "quill-scholar", quantity: 1 }],
      achievements: ["knowledge-seeker"]
    },
    status: "locked",
    miniGame: "strategy",
    miniGameConfig: { type: "strategy", difficulty: 5, timeLimit: 200, passingScore: 70 },
    energyCost: 22,
    estimatedTime: 18,
    repeatability: "once",
    completionCount: 0,
    storyline: "air-knowledge",
    prerequisites: ["air-know-3"],
  },
];

// ============================================
// EXPANDED QUESTS - WATER REALM
// ============================================

export const WATER_QUESTS: Quest[] = [
  // Still Waters Storyline
  {
    id: "water-aware-1",
    name: "Inner Reflection",
    description: "Begin your journey of emotional awareness.",
    longDescription: "Before you can navigate the waters of emotion, you must first learn to see clearly into your own depths. This quest begins your journey of self-awareness.",
    realm: "water",
    difficulty: "beginner",
    chapter: 1,
    requirements: {},
    rewards: { experience: 50, tokens: 10, statBoosts: { water: 2 } },
    status: "available",
    miniGame: "reflection",
    miniGameConfig: { type: "reflection", difficulty: 1, questionCount: 3, passingScore: 60 },
    energyCost: 10,
    estimatedTime: 5,
    repeatability: "daily",
    completionCount: 0,
    storyline: "water-awareness",
    npcGiver: "healer-tide",
  },
  {
    id: "water-aware-2",
    name: "Naming Emotions",
    description: "Learn to identify and name your feelings.",
    longDescription: "We cannot address what we cannot name. Develop your emotional vocabulary and learn to precisely identify what you're feeling.",
    realm: "water",
    difficulty: "beginner",
    chapter: 1,
    requirements: { stats: { water: 2 } },
    rewards: { experience: 75, tokens: 15, statBoosts: { water: 2, air: 1 } },
    status: "locked",
    miniGame: "trivia",
    miniGameConfig: { type: "trivia", difficulty: 2, questionCount: 5, passingScore: 60 },
    energyCost: 12,
    estimatedTime: 8,
    repeatability: "once",
    completionCount: 0,
    storyline: "water-awareness",
    prerequisites: ["water-aware-1"],
  },
  {
    id: "water-aware-3",
    name: "Emotional Triggers",
    description: "Identify what triggers your emotional responses.",
    longDescription: "Understanding your triggers is the first step to mastering your responses. Map the situations, words, and events that spark strong emotions.",
    realm: "water",
    difficulty: "intermediate",
    chapter: 1,
    requirements: { stats: { water: 4 } },
    rewards: { experience: 100, tokens: 20, statBoosts: { water: 3 } },
    status: "locked",
    miniGame: "reflection",
    miniGameConfig: { type: "reflection", difficulty: 3, questionCount: 4, passingScore: 65 },
    energyCost: 15,
    estimatedTime: 10,
    repeatability: "once",
    completionCount: 0,
    storyline: "water-awareness",
    prerequisites: ["water-aware-2"],
  },
  {
    id: "water-aware-4",
    name: "Body Wisdom",
    description: "Learn to read your body's emotional signals.",
    longDescription: "Your body speaks before your mind understands. Learn to recognize the physical sensations that accompany different emotions.",
    realm: "water",
    difficulty: "intermediate",
    chapter: 1,
    requirements: { stats: { water: 6 } },
    rewards: { experience: 125, tokens: 25, statBoosts: { water: 3, self: 1 } },
    status: "locked",
    miniGame: "meditation",
    miniGameConfig: { type: "meditation", difficulty: 3, timeLimit: 60, passingScore: 100 },
    energyCost: 15,
    estimatedTime: 12,
    repeatability: "daily",
    completionCount: 0,
    storyline: "water-awareness",
    prerequisites: ["water-aware-3"],
  },
  {
    id: "water-aware-5",
    name: "The Observer's Mind",
    description: "Develop the ability to observe emotions without reaction.",
    longDescription: "The highest form of emotional awareness is the ability to observe your feelings without being controlled by them. Cultivate the observer's mind.",
    realm: "water",
    difficulty: "advanced",
    chapter: 1,
    requirements: { stats: { water: 8 } },
    rewards: { 
      experience: 200, 
      tokens: 40, 
      statBoosts: { water: 5 },
      achievements: ["emotional-awareness"]
    },
    status: "locked",
    miniGame: "meditation",
    miniGameConfig: { type: "meditation", difficulty: 4, timeLimit: 90, passingScore: 100 },
    energyCost: 20,
    estimatedTime: 15,
    repeatability: "once",
    completionCount: 0,
    storyline: "water-awareness",
    prerequisites: ["water-aware-4"],
  },

  // Currents of Healing Storyline
  {
    id: "water-heal-1",
    name: "Acknowledging Wounds",
    description: "Begin the healing process by acknowledging past hurts.",
    longDescription: "Healing begins with acknowledgment. In this quest, you'll learn to recognize and accept the wounds you carry without judgment.",
    realm: "water",
    difficulty: "intermediate",
    chapter: 2,
    requirements: { stats: { water: 10 } },
    rewards: { experience: 100, tokens: 25, statBoosts: { water: 3 } },
    status: "locked",
    miniGame: "reflection",
    miniGameConfig: { type: "reflection", difficulty: 4, questionCount: 4, passingScore: 70 },
    energyCost: 15,
    estimatedTime: 10,
    repeatability: "once",
    completionCount: 0,
    storyline: "water-healing",
    prerequisites: ["water-aware-5"],
    npcGiver: "healer-tide",
  },
  {
    id: "water-heal-2",
    name: "The Forgiveness Path",
    description: "Learn the power of forgiveness—for others and yourself.",
    longDescription: "Forgiveness is not about others—it's about freeing yourself. Learn techniques for releasing resentment and finding peace.",
    realm: "water",
    difficulty: "intermediate",
    chapter: 2,
    requirements: { stats: { water: 12 } },
    rewards: { experience: 125, tokens: 30, statBoosts: { water: 3, land: 1 } },
    status: "locked",
    miniGame: "reflection",
    miniGameConfig: { type: "reflection", difficulty: 4, questionCount: 5, passingScore: 70 },
    energyCost: 15,
    estimatedTime: 12,
    repeatability: "once",
    completionCount: 0,
    storyline: "water-healing",
    prerequisites: ["water-heal-1"],
  },
  {
    id: "water-heal-3",
    name: "Breaking Cycles",
    description: "Identify and break negative emotional patterns.",
    longDescription: "Many wounds are inherited—patterns passed down through generations. Learn to identify these cycles and consciously choose a different path.",
    realm: "water",
    difficulty: "advanced",
    chapter: 2,
    requirements: { stats: { water: 14 } },
    rewards: { experience: 175, tokens: 40, statBoosts: { water: 4, land: 2 } },
    status: "locked",
    miniGame: "puzzle",
    miniGameConfig: { type: "puzzle", difficulty: 5, timeLimit: 180, passingScore: 70 },
    energyCost: 18,
    estimatedTime: 15,
    repeatability: "once",
    completionCount: 0,
    storyline: "water-healing",
    prerequisites: ["water-heal-2"],
  },
  {
    id: "water-heal-4",
    name: "The Healer's Heart",
    description: "Transform your wounds into wisdom for helping others.",
    longDescription: "Your greatest wounds can become your greatest gifts. Learn to use your healing journey to help others on their path.",
    realm: "water",
    difficulty: "advanced",
    chapter: 2,
    requirements: { stats: { water: 16 } },
    rewards: { 
      experience: 250, 
      tokens: 60, 
      statBoosts: { water: 5, air: 2 },
      achievements: ["healer-awakened"]
    },
    status: "locked",
    miniGame: "reflection",
    miniGameConfig: { type: "reflection", difficulty: 5, questionCount: 5, passingScore: 75 },
    energyCost: 22,
    estimatedTime: 18,
    repeatability: "once",
    completionCount: 0,
    storyline: "water-healing",
    prerequisites: ["water-heal-3"],
  },
];

// ============================================
// EXPANDED QUESTS - SELF REALM
// ============================================

export const SELF_QUESTS: Quest[] = [
  // The Inner Flame Storyline
  {
    id: "self-purpose-1",
    name: "Purpose Discovery",
    description: "Begin identifying your core values.",
    longDescription: "Before you can build wealth, you must know why you're building it. This quest helps you identify your core values and begin defining your life's purpose.",
    realm: "self",
    difficulty: "beginner",
    chapter: 1,
    requirements: {},
    rewards: { experience: 50, tokens: 10, statBoosts: { self: 2 } },
    status: "available",
    miniGame: "reflection",
    miniGameConfig: { type: "reflection", difficulty: 1, questionCount: 3, passingScore: 60 },
    energyCost: 10,
    estimatedTime: 5,
    repeatability: "once",
    completionCount: 0,
    storyline: "self-purpose",
    npcGiver: "mentor-flame",
  },
  {
    id: "self-purpose-2",
    name: "Strengths Inventory",
    description: "Identify your natural talents and abilities.",
    longDescription: "Everyone has unique gifts. Discover your natural strengths and learn how they can serve your purpose.",
    realm: "self",
    difficulty: "beginner",
    chapter: 1,
    requirements: { stats: { self: 2 } },
    rewards: { experience: 75, tokens: 15, statBoosts: { self: 2, air: 1 } },
    status: "locked",
    miniGame: "trivia",
    miniGameConfig: { type: "trivia", difficulty: 2, questionCount: 5, passingScore: 60 },
    energyCost: 12,
    estimatedTime: 8,
    repeatability: "once",
    completionCount: 0,
    storyline: "self-purpose",
    prerequisites: ["self-purpose-1"],
  },
  {
    id: "self-purpose-3",
    name: "Vision Crafting",
    description: "Create a vision for your ideal future.",
    longDescription: "A clear vision pulls you forward. Craft a compelling picture of the future you want to create.",
    realm: "self",
    difficulty: "intermediate",
    chapter: 1,
    requirements: { stats: { self: 4 } },
    rewards: { experience: 100, tokens: 20, statBoosts: { self: 3 } },
    status: "locked",
    miniGame: "reflection",
    miniGameConfig: { type: "reflection", difficulty: 3, questionCount: 4, passingScore: 65 },
    energyCost: 15,
    estimatedTime: 10,
    repeatability: "once",
    completionCount: 0,
    storyline: "self-purpose",
    prerequisites: ["self-purpose-2"],
  },
  {
    id: "self-purpose-4",
    name: "Mission Statement",
    description: "Write your personal mission statement.",
    longDescription: "Distill your purpose into a clear, actionable mission statement that will guide your decisions.",
    realm: "self",
    difficulty: "intermediate",
    chapter: 1,
    requirements: { stats: { self: 6 } },
    rewards: { experience: 125, tokens: 25, statBoosts: { self: 3, air: 1 } },
    status: "locked",
    miniGame: "word",
    miniGameConfig: { type: "word", difficulty: 3, timeLimit: 120, passingScore: 65 },
    energyCost: 15,
    estimatedTime: 12,
    repeatability: "once",
    completionCount: 0,
    storyline: "self-purpose",
    prerequisites: ["self-purpose-3"],
  },
  {
    id: "self-purpose-5",
    name: "The Purpose Alignment",
    description: "Align your daily actions with your purpose.",
    longDescription: "Purpose without action is just a dream. Learn to align your daily choices with your larger mission.",
    realm: "self",
    difficulty: "advanced",
    chapter: 1,
    requirements: { stats: { self: 8 } },
    rewards: { 
      experience: 200, 
      tokens: 40, 
      statBoosts: { self: 5 },
      achievements: ["purpose-found"]
    },
    status: "locked",
    miniGame: "strategy",
    miniGameConfig: { type: "strategy", difficulty: 4, timeLimit: 180, passingScore: 70 },
    energyCost: 20,
    estimatedTime: 15,
    repeatability: "once",
    completionCount: 0,
    storyline: "self-purpose",
    prerequisites: ["self-purpose-4"],
  },

  // Building Blocks Storyline
  {
    id: "self-found-1",
    name: "Financial Foundation",
    description: "Learn the basics of budgeting and saving.",
    longDescription: "Every great fortune starts with a solid foundation. This quest teaches you the fundamentals of budgeting, saving, and building financial security.",
    realm: "self",
    difficulty: "intermediate",
    chapter: 2,
    requirements: { stats: { self: 10 } },
    rewards: { experience: 100, tokens: 25, statBoosts: { self: 3 } },
    status: "locked",
    miniGame: "math",
    miniGameConfig: { type: "math", difficulty: 3, questionCount: 5, passingScore: 60 },
    energyCost: 15,
    estimatedTime: 10,
    repeatability: "once",
    completionCount: 0,
    storyline: "self-foundation",
    prerequisites: ["self-purpose-5"],
    npcGiver: "mentor-flame",
  },
  {
    id: "self-found-2",
    name: "Debt Freedom",
    description: "Create a strategy to eliminate debt.",
    longDescription: "Debt is a chain that binds your future. Learn strategies for systematically eliminating debt and freeing yourself.",
    realm: "self",
    difficulty: "intermediate",
    chapter: 2,
    requirements: { stats: { self: 12 } },
    rewards: { experience: 125, tokens: 30, statBoosts: { self: 3, water: 1 } },
    status: "locked",
    miniGame: "math",
    miniGameConfig: { type: "math", difficulty: 4, questionCount: 6, passingScore: 65 },
    energyCost: 15,
    estimatedTime: 12,
    repeatability: "once",
    completionCount: 0,
    storyline: "self-foundation",
    prerequisites: ["self-found-1"],
  },
  {
    id: "self-found-3",
    name: "Emergency Reserves",
    description: "Build your financial safety net.",
    longDescription: "Security comes from preparation. Learn to build and maintain an emergency fund that protects you from life's uncertainties.",
    realm: "self",
    difficulty: "advanced",
    chapter: 2,
    requirements: { stats: { self: 14 } },
    rewards: { experience: 175, tokens: 40, statBoosts: { self: 4 } },
    status: "locked",
    miniGame: "strategy",
    miniGameConfig: { type: "strategy", difficulty: 4, timeLimit: 150, passingScore: 70 },
    energyCost: 18,
    estimatedTime: 15,
    repeatability: "once",
    completionCount: 0,
    storyline: "self-foundation",
    prerequisites: ["self-found-2"],
  },
  {
    id: "self-found-4",
    name: "Investment Basics",
    description: "Learn the fundamentals of growing wealth.",
    longDescription: "Money must work for you. Learn the basics of investing and how to make your money grow over time.",
    realm: "self",
    difficulty: "advanced",
    chapter: 2,
    requirements: { stats: { self: 16 } },
    rewards: { 
      experience: 250, 
      tokens: 60, 
      statBoosts: { self: 5, air: 2 },
      achievements: ["financial-foundation"]
    },
    status: "locked",
    miniGame: "trivia",
    miniGameConfig: { type: "trivia", difficulty: 5, questionCount: 7, passingScore: 70 },
    energyCost: 22,
    estimatedTime: 18,
    repeatability: "once",
    completionCount: 0,
    storyline: "self-foundation",
    prerequisites: ["self-found-3"],
  },
];

// ============================================
// COMBINED EXPANDED QUESTS
// ============================================

export const EXPANDED_QUESTS: Quest[] = [
  ...LAND_QUESTS,
  ...AIR_QUESTS,
  ...WATER_QUESTS,
  ...SELF_QUESTS,
];

// Helper function to get quests by storyline
export function getQuestsByStoryline(storylineId: string): Quest[] {
  return EXPANDED_QUESTS.filter(quest => quest.storyline === storylineId);
}

// Helper function to get storyline progress
export function getStorylineProgress(storylineId: string, completedQuests: string[]): { completed: number; total: number; percentage: number } {
  const storyline = STORYLINES.find(s => s.id === storylineId);
  if (!storyline) return { completed: 0, total: 0, percentage: 0 };
  
  const completed = storyline.questIds.filter(id => completedQuests.includes(id)).length;
  const total = storyline.questIds.length;
  const percentage = total > 0 ? Math.round((completed / total) * 100) : 0;
  
  return { completed, total, percentage };
}

// Helper function to check if storyline is unlocked
export function isStorylineUnlocked(storylineId: string, level: number, completedStorylines: string[]): boolean {
  const storyline = STORYLINES.find(s => s.id === storylineId);
  if (!storyline) return false;
  if (!storyline.unlockRequirements) return true;
  
  const { level: reqLevel, completedStorylines: reqStorylines } = storyline.unlockRequirements;
  
  if (reqLevel && level < reqLevel) return false;
  if (reqStorylines) {
    for (const req of reqStorylines) {
      if (!completedStorylines.includes(req)) return false;
    }
  }
  
  return true;
}
